### ISSUE TITLE
Game crashing when i play a mod song (IOS)

### ISSUE THREAD

**Issue by BreadStock** [MobilePorting/FNF-PsychEngine-Mobile#100]
### Describe your bug here.

When i play a song from the main weeks, it doesn’t crash. But when i play a mod that i imported, it crashes.

### Crash Log or logcat logs (if existing)

Null Object Reference
../../../../../source/states/PlayState.hx [line 945]
../../../../../source/backend/BaseStage.hx [line 118]
../../../../../source/states/stages/School.hx [line 117]
../../../../../source/states/stages/School.hx [line 87]
../../../../../source/backend/BaseStage.hx [line 58]
../../../../../source/states/stages/School.hx [line 9]
../../../../../source/states/PlayState.hx [line 397]
flixel/FlxGame.hx [line 642]
flixel/FlxGame.hx [line 729]
flixel/FlxGame.hx [line 682]
flixel/FlxGame.hx [line 556]
openfl/events/EventDispatcher.hx [line 444]
openfl/display/DisplayObject.hx [line 1400]

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

iOS

### Did you edit anything in this build? If so, mention or summarize your changes.

I didn’t edit anything.

**Comment by mcagabe19** [comment]
what mod you trying to play? can be ram issue

**Comment by mcagabe19** [comment]
@BreadStock are you using devbuild

**Comment by BreadStock** [comment]
> @BreadStock are you using devbuild cuz 0.7.3 release for iOS can be buggy

Yeah im using the latest (0.7.3)

**Comment by BreadStock** [comment]
the mod plays for a split second but crashes immediately. seems like the main week is also crashing when i play too much of them. could be my iphone’s fault (im using iphone 6) so im closing this.

**Comment by BreadStock** [comment]
the mod plays for a split second but crashes immediately. seems like the main week is also crashing when i play too much of them. could be my iphone’s fault (im using iphone 6) so im closing this.

**Comment by moxie-coder** [comment]
> the mod plays for a split second but crashes immediately. seems like the main week is also crashing when i play too much of them. could be my iphone’s fault (im using iphone 6) so im closing this.

then you might just have an outdated phone (literally discontinued) and iOS, I would probably wait until you get a new phone
