### ISSUE TITLE
I can't install mods in the dev build 

### ISSUE THREAD

**Issue by AStupidPersonXd123** [MobilePorting/FNF-PsychEngine-Mobile#101]
### Describe your bug here.

Android

### Crash Log or logcat logs (if existing)

```bash
I get an error when opening the free play, the editor character, the week editor and etc.
```

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by moxie-coder** [comment]
can you show us the errors?

**Comment by AStupidPersonXd123** [comment]
wait

**Comment by mcagabe19** [comment]
needed update devbuild
