### ISSUE TITLE
Record Problem

### ISSUE THREAD

**Issue by AliAlafandy** [MobilePorting/FNF-PsychEngine-Mobile#103]
### Describe your bug here.

When I recording the game: no sounds and music.
information: It has been activated inner voice (not microphone, mute or (microphone and inner voice))

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't

**Comment by mcagabe19** [comment]
EXTERNAL and MEDIA doesn't have recording support and it's a wontfix plus if you have android 10 down you can't record with internal audio

**Comment by AliAlafandy** [comment]
Oh Hell
