### ISSUE TITLE
UI elements move as if they were part of the game

### ISSUE THREAD

**Issue by keratomalacian** [MobilePorting/FNF-PsychEngine-Mobile#105]
### Describe your bug here.

Some elements like the touch controls, time bar and progress bar are out of place and they move as if they are on camGame, when they should be static since they are UI elements. However, this doesnt happen to other elements like the player/enemy icons.

https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/162604540/14d8034d-62fa-4741-8142-8e0934fd43d0

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No, this is the unmodified source code for the 0.7.3 release

**Comment by mcagabe19** [comment]
we only fix 1.0a issues this is outdated for us
