### ISSUE TITLE
When the song starts, a lot of identical errors appear abruptly on the full screen on version 1.0a DevBuild 90494e3

### ISSUE THREAD

**Issue by The1NikitosPlay** [MobilePorting/FNF-PsychEngine-Mobile#106]
### Describe your bug here.

When a song starts, I immediately have a bunch of full-screen errors on my screen, and the cutscenes inside the song that should be in this song do not work
I can show you a good example right on the video and screenshot

https://drive.google.com/drive/folders/1zNpIelM-PobD8lLrKxBBYLodqwxz6sY3

### Crash Log or logcat logs (if existing)

```bash
I'll just share a screenshot and a video showing all the errors.
```

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I'm just installing mods for this engine.

**Comment by The1NikitosPlay** [comment]
![Uploading Screenshot_2024-04-21-10-26-11-548_com.shadowmario.psychengine.jpg…]()

**Comment by KarimAkra** [comment]
Outdated mod that is in company with newer version
