### ISSUE TITLE
Cannot copy all files directly to EXTERNAL and EXTERNAL_MEDIA folder

### ISSUE THREAD

**Issue by Stefan2008Git** [MobilePorting/FNF-PsychEngine-Mobile#108]
### Describe your bug here.

It seems like it cannot move files to EXTERNAL type of storage for me as you can see
![Screenshot_2024-05-03-02-42-20-275_com shadowmario psychengine](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/126715034/702c8392-736e-4d5a-8ea3-5bdd39e8094b)

### Crash Log or logcat logs (if existing)

```bash
Cannot paste them because they are not exists
```

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

Nah, i am simply here to report some people issue

**Comment by Stefan2008Git** [comment]
One thing i forgot to mention is even if i try with SD card method, it will give the same error

**Comment by mcagabe19** [comment]
since I don't have an android 14 phone, nothing much I can do api may changed on android 14 or permissions not granted

**Comment by Stefan2008Git** [comment]
> since I don't have an android 14 phone, nothing much I can do. API may changed on android 14 or permissions not granted

I accepted the permission tho. It doesn't want to copy all files from application to external storage

**Comment by mcagabe19** [comment]
@Stefan2008Git I tested at android virtual device, it work on both 14 and 15 so uhh did u give all files access to psych engine? (Settings > Apps > Special app access > All files access)

**Comment by Stefan2008Git** [comment]
> @Stefan2008Git I tested at android virtual device, it work on both 14 and 15 so uhh did u give all files access to psych engine? (Settings > Apps > Special app access > All files access)

It automatically switches to "Special app access" and i accepted :/

**Comment by mcagabe19** [comment]
well then nothing I can do about it
