### ISSUE TITLE
Game frezzes every time a add a mod into it

### ISSUE THREAD

**Issue by forevernenaa** [MobilePorting/FNF-PsychEngine-Mobile#11]
### Describe your bug here.

Hi so when i port a mod the game opens it but when she starts singing it frezzes the notes goes down up down up down up a millian times

### Crash Log or logcat logs (if existing)

```bash
And some times it crashes
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No i dint edit anything

**Comment by mcagabe19** [comment]
we needed a video

**Comment by mcagabe19** [comment]
closing issue due no reply
