### ISSUE TITLE
The Songs Are Crashing

### ISSUE THREAD

**Issue by Luansilv16** [MobilePorting/FNF-PsychEngine-Mobile#110]
### Describe your bug here.

every time I go into any song

### Crash Log or logcat logs (if existing)

```bash
U
```

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes

**Comment by moxie-coder** [comment]
we need more info

**Comment by mcagabe19** [comment]
L + ratio + get better device
