### ISSUE TITLE
How can I open editor in DevBuild 3a014cc

### ISSUE THREAD

**Issue by AliAlafandy** [MobilePorting/FNF-PsychEngine-Mobile#111]
### Describe your problem here.

https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/107328467/6716ac3f-6e9c-4fa0-ba40-880706065506

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't

**Comment by moxie-coder** [comment]
the two other buttons: am I a joke to you?
