### ISSUE TITLE
I can't access the data and it's from android EXTERNAL 

### ISSUE THREAD

**Issue by AStupidPersonXd123** [MobilePorting/FNF-PsychEngine-Mobile#112]
### Describe your problem here.

https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/166671910/78e4f86a-b403-403c-b2c9-d5d14b12992b

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by AStupidPersonXd123** [comment]
![week-12-leak](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/166671910/3b72eb8a-8d94-4791-9646-6fd618504c16)

**Comment by moxie-coder** [comment]
there is an setting is mobile settings for EXTERNAL
