### ISSUE TITLE
I can't press the buttons to play 

### ISSUE THREAD

**Issue by AStupidPersonXd123** [MobilePorting/FNF-PsychEngine-Mobile#113]
### Describe your bug here.

When I press the screen it sends me to achievements and not anywhere, please solve it:( 

### Crash Log or logcat logs (if existing)

```bash
No I have
```

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by moxie-coder** [comment]
this needs more info

**Comment by moxie-coder** [comment]
actually wait no, because there is up and down buttons

**Comment by mcagabe19** [comment]
overlaps needs to be fixed so reopened

**Comment by moxie-coder** [comment]
oh okay

**Comment by AStupidPersonXd123** [comment]
👍

**Comment by AStupidPersonXd123** [comment]
but when I push it I get achievements:v

**Comment by AStupidPersonXd123** [comment]
Close

**Comment by mcagabe19** [comment]
fixed
