### ISSUE TITLE
I just fucked up to fix it pls help me!!!

### ISSUE THREAD

**Issue by Jordanmladshi** [MobilePorting/FNF-PsychEngine-Mobile#115]
### Describe your bug here.

When i added the mods to mod folder and i want to play the week but came that shit
![IMG_2097](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/169258589/177c915b-bcfb-4920-98e7-197e1ae0f81e)
I downloaded fnf with altstore 
Sorry if i write with mistakes i dont speak english

### Crash Log or logcat logs (if existing)

```bash
assets/fonts/vcr.ttf (Null Object Reference)
assets/fonts/pixel.otf (Null Object Reference)
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

iOS

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by moxie-coder** [comment]
missing json file

**Comment by Jordanmladshi** [comment]
I dont have even missen json files in game directory i just checked out
