### ISSUE TITLE
help i got a problem

### ISSUE THREAD

**Issue by MaximumX64** [MobilePorting/FNF-PsychEngine-Mobile#117]
### Describe your problem here.

i was compiling the source code and this happend
![Captura](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/167785527/ad013958-2b0d-43fe-877b-4da8f5cdefbd)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

yes but only for that type not found: teacall

**Comment by mcagabe19** [comment]
update extension-androidtools

**Comment by MaximumX64** [comment]
it told me that was already updated

**Comment by MaximumX64** [comment]
but i still tried and i got the same error

**Comment by mcagabe19** [comment]
hmm, then downgrade

**Comment by MaximumX64** [comment]
And how do i do that?

**Comment by mcagabe19** [comment]
like `haxelib install extension-androidtools 1.9.0`

**Comment by MaximumX64** [comment]
ok imma try

**Comment by MaximumX64** [comment]
i did downgrade but the error still didn't get fixed

**Comment by MaximumX64** [comment]
it always get me this 
![Captura](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/167785527/0e2cfbc1-d66b-4894-9e07-33754f067865)

**Comment by mcagabe19** [comment]
keep trying downgrading and see versions list from https://lib.haxe.org/p/extension-androidtools

**Comment by MaximumX64** [comment]
iam still getting this
![help](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/167785527/bb23a9db-6182-44f6-9bc5-f271a342dd2a)

**Comment by MaximumX64** [comment]
iam still getting this
![Captura](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/167785527/5d77f070-c80c-414b-8235-57766efee7e9)

**Comment by MaximumX64** [comment]
and i downgraded to 1.8.3

**Comment by kennay-egg** [comment]
hello 👋

**Comment by MaximumX64** [comment]
hi, i just need help

**Comment by KarimAkra** [comment]
run `haxelib set extension-androidtools 2.0.0`
