### ISSUE TITLE
how scripts work

### ISSUE THREAD

**Issue by kennay-egg** [MobilePorting/FNF-PsychEngine-Mobile#119]
### Describe your problem here.

How do scripts work when you put them in the mods folder?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

**Comment by mcagabe19** [comment]
https://github.com/MobilePorting/FNF-PsychEngine-Mobile/wiki/Installing-Mods

**Comment by mcagabe19** [comment]
and go ask this to psych repo or server instead
