### ISSUE TITLE
something annoying

### ISSUE THREAD

**Issue by noobcubestuff** [MobilePorting/FNF-PsychEngine-Mobile#120]
### What is your question?

why is it saying the app conflicts with another package

**Comment by KarimAkra** [comment]
Check your installed fnf mods
If any of them is psych engine delete it and try installing the apk again
If the error persist the only fixes i know is by connecting your phone to a computer, enable USB Debugging install adb and run `adb uninstall com.shadowmario.psychengine` in CMD or a factory reset
