### ISSUE TITLE
Widescreen + Widescreen Hitbox Controls

### ISSUE THREAD

**Issue by CycloKid** [MobilePorting/FNF-PsychEngine-Mobile#121]
### What is your question?

Im wondering about support for more widescreen aspect ratios such as 21:9, 20:9, 19.5:9 and others. If I might have missed and it is already there, that maybe an extra setting ingame for auto-resolution/auto-aspect-ratio and manually configuring it.
Another part of this feature im particularly interested about is being able to use the further edges of the screen for hitbox controls. I tend to use middlescroll most often, so if I could be able to keep my fingers just a little bit more away from the area where you see notes coming from it makes it more playable in my experience.

Thanks in advance!
  - CycloKid

**Comment by KarimAkra** [comment]
FNF is a game that runs in a 1280x720 resolution
making it run any resolution higher than that will result in breaking the game visuals and making everything smaller
if it was possible or easy to make only the hitbox support a resolution higher than 1280x720 it would've been done long ago
so our answer is simply no, we're unable to make the game run a resolution higher than 1280x720
