### ISSUE TITLE
Another problem

### ISSUE THREAD

**Issue by MaximumX64** [MobilePorting/FNF-PsychEngine-Mobile#122]
### Describe your problem here.

last time i had an error now it's fixed but now we have this one
![again](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/167785527/b3ee8c4d-56dc-4081-8799-228cdccd201c)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

yes but only for that type not found: teacall

**Comment by MaximumX64** [comment]
if you don't understand spanish the text said "not reconized as internal, external,  program nor any executable file

**Comment by KarimAkra** [comment]
Download the r21e android NDK  from [here](https://github.com/android/ndk/wiki/Unsupported-Downloads)
Extract it anywhere you want and run `lime setup android` placing the appropriate path to where you extracted the NDK
Also make sure you downloaded android 4.4 KitKat SDK from android studio and JDK 11 or 17
They all should go in the appropriate section when running `lime setup android`

**Comment by MaximumX64** [comment]
I'm going to try

**Comment by MaximumX64** [comment]
![plz](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/167785527/3ce97a78-050f-4639-95e3-6539edf1d122)
now i'm getting this

**Comment by MaximumX64** [comment]
and it's still going

**Comment by KarimAkra** [comment]
Good it's compiling

**Comment by MaximumX64** [comment]
And plz don't just close as completed everytime you think that it's fixed

**Comment by MaximumX64** [comment]
+ I put to emulate to my phone and still nothing

**Comment by MaximumX64** [comment]
![1](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/167785527/2927fa46-7b83-4dd3-9546-9246e0c3e1c6)
![2](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/167785527/683f38b0-e60f-4feb-b8b3-cae575bfea14)
I'm only getting this at the end

**Comment by MaximumX64** [comment]
im going to try

**Comment by MaximumX64** [comment]
i have this
![Captura](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/167785527/be97583f-da3c-44e8-a8ba-3abc39ea473b)
 and yes i upgraded sscript

**Comment by MaximumX64** [comment]
then i opend setup-windows then i upgraded every one of those but i still getting the same error
