### ISSUE TITLE
I have error before launches PE

### ISSUE THREAD

**Issue by MishaFNF** [MobilePorting/FNF-PsychEngine-Mobile#125]
### Describe your bug here.

![Screenshot_20240519_115113_com shadowmario psychengine](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/167096853/bb7c833f-ee25-49e6-80e1-96efaaed4072)

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes

**Comment by KarimAkra** [comment]
Can i know which build you're using?

**Comment by MishaFNF** [comment]
> Can i know which build you're using?

Yes

**Comment by KarimAkra** [comment]
Try moving any of your mods into somewhere so they won't get deleted
Open settings and clear the app data
Load the game again (it will copy assets on its own) and stick to EXTERNAL_DATA or EXTERNAL_OBB
You're using android 10 they work fine and are faster than EXTERNAL and MEDIA

**Comment by KarimAkra** [comment]
If it's still doing this i suggest you use [0.7.3](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/releases/tag/0.7.3)
Scripts are more stable in that version so it'll be better for you

**Comment by MishaFNF** [comment]
> Try moving any of your mods into somewhere so they won't get deleted Open settings and clear the app data Load the game again (it will copy assets on its own) and stick to EXTERNAL_DATA or EXTERNAL_OBB You're using android 10 they work fine and are faster than EXTERNAL and MEDIA

Thanks, but look on pictrue
![Screenshot_20240519_104107_com shadowmario psychengine](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/167096853/6aaa9766-2e8f-4baa-8de6-e47ef8d7a8aa)

**Comment by MishaFNF** [comment]
> > Try moving any of your mods into somewhere so they won't get deleted Open settings and clear the app data Load the game again (it will copy assets on its own) and stick to EXTERNAL_DATA or EXTERNAL_OBB You're using android 10 they work fine and are faster than EXTERNAL and MEDIA
> 
> Thanks, but look on pictrue ![Screenshot_20240519_104107_com shadowmario psychengine](https://private-user-images.githubusercontent.com/167096853/331855981-6aaa9766-2e8f-4baa-8de6-e47ef8d7a8aa.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMDU0NzIsIm5iZiI6MTcxNjEwNTE3MiwicGF0aCI6Ii8xNjcwOTY4NTMvMzMxODU1OTgxLTZhYWE5NzY2LTJlOGYtNGJhYS04ZGU2LWU0N2VmOGQ3YThhYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOVQwNzUyNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjczYjE0NTZkZjRjYWMwMGZkZjA2ZDE3N2VkZTdhNTJhMDAxOTMzMjQwZDYzMTk4NjYxMDViM2NiODhhZmM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m07D85JVb2jPk8r_Z32aGyAkpvaMqS9zcWhfb_j1lU8)

And
![Screenshot_20240519_145221_com shadowmario psychengine](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/167096853/be75af27-a207-43f8-bea9-b5cca5a749b4)
