### ISSUE TITLE
Cant installed

### ISSUE THREAD

**Issue by ARYABAKRI1** [MobilePorting/FNF-PsychEngine-Mobile#126]
### Describe your bug here.

The apk cant installed and need update node.js and anothers
![Screenshot_20240519-142910](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/96322441/c07d1ea4-6c80-46cc-8988-179238559751)

### Crash Log or logcat logs (if existing)

```bash
Need update node.js
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by moxie-coder** [comment]
they're right below that you retarded fuck
