### ISSUE TITLE
Install Mods in PE 1.0b

### ISSUE THREAD

**Issue by MishaFNF** [MobilePorting/FNF-PsychEngine-Mobile#127]
### What is your question?

How to add mods in PE 1.0b? 

![Screenshot_20240519_155145_com shadowmario psychengine](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/167096853/bdf253f1-2435-4b7c-a51d-5218e2c12311)

**Comment by KarimAkra** [comment]
https://github.com/MobilePorting/FNF-PsychEngine-Mobile/wiki/Installing-Mods

**Comment by MishaFNF** [comment]
> https://github.com/MobilePorting/FNF-PsychEngine-Mobile/wiki/Installing-Mods

Thanks
