### ISSUE TITLE
How to add lua??? And add lua in the song?

### ISSUE THREAD

**Issue by 5tupidBoy** [MobilePorting/FNF-PsychEngine-Mobile#128]
### Describe your problem here.

How to add lua and
Add lua in folder data

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

**Comment by mcagabe19** [comment]
goto your directory (https://github.com/MobilePorting/FNF-PsychEngine-Mobile/wiki/Installing-Mods) and create scripts folder

**Comment by 5tupidBoy** [comment]
No I mean in source code

**Comment by moxie-coder** [comment]
you don’t need source code for that
