### ISSUE TITLE
again

### ISSUE THREAD

**Issue by MaximumX64** [MobilePorting/FNF-PsychEngine-Mobile#129]
### Describe your problem here.

sorry for molestation but plz help
![Captura](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/167785527/de8242ec-20f1-41b4-9931-83b683e00584)
btw i did update everything

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

yes but only for that type not found: teacall

**Comment by MaximumX64** [comment]
plz

**Comment by MaximumX64** [comment]
btw i already upgraded sscript and everything else
so that's not the problem

**Comment by kviks** [comment]
are you fix that? i have same problem

**Comment by mcagabe19** [comment]
add `<haxedef name="DISABLED_MACRO_SUPERLATIVE" if="mobile" />` in `Project.xml`.

**Comment by MaximumX64** [comment]
i added it at the end and got this
![image](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/167785527/7990c52f-d13f-4209-bd80-b99617163285)

**Comment by mcagabe19** [comment]
old SScript

**Comment by MaximumX64** [comment]
what version

**Comment by MaximumX64** [comment]
![image](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/167785527/b26773bd-e106-41cd-bd34-42eba7dc4d14)

**Comment by MaximumX64** [comment]
sscript is up to date
