### ISSUE TITLE
Error with Tools.obj

### ISSUE THREAD

**Issue by Fearester2008** [MobilePorting/FNF-PsychEngine-Mobile#131]
### Describe your problem here.

This error won't compile my code
![Screenshot_20240521-134701](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/131034025/b3ccb86a-632f-4cfc-90f0-bc76989cbe7b)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Desktop (Linux, Windows or Mac)

**Comment by moxie-coder** [comment]
issues with your engine are not our problem

**Comment by Fearester2008** [comment]
I give code from this

**Comment by moxie-coder** [comment]
> I give code from this

if you modified it in a way or used code from this that is far different from this port, it is still not a valid issue
