### ISSUE TITLE
what i need to do

### ISSUE THREAD

**Issue by kviks** [MobilePorting/FNF-PsychEngine-Mobile#133]
### Describe your problem here.

What i need to do?
I using NDK r21e
Java 11
SScript updated

![image](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/85123677/eb352418-c53d-45e9-a583-f7aa5e6b4436)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
add `<haxedef name="DISABLED_MACRO_SUPERLATIVE" if="mobile" />` in `Project.xml`.
