### ISSUE TITLE
how fix that:x

### ISSUE THREAD

**Issue by kviks** [MobilePorting/FNF-PsychEngine-Mobile#135]
### Describe your problem here.

I'm using JDK 11

![image](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/85123677/3b16c575-cc5c-40b5-bd95-90a0c9794100)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, main, fpscounter, mainmenu

**Comment by KarimAkra** [comment]
This happens randomly and it's a lime issue
Just try building again

**Comment by kviks** [comment]
> This happens randomly and it's a lime issue Just try building again

i need delete export?

**Comment by kviks** [comment]
> This happens randomly and it's a lime issue Just try building again

nothing helping, ill delete export 3 times and i still have that

**Comment by KarimAkra** [comment]
You don't need to delete export
Make sure you're using our lime fork (which can be found in hmm.jsom) because we fixed this issue in it

**Comment by KarimAkra** [comment]
Did you get it fixed?

**Comment by kviks** [comment]
> Did you get it fixed?

ye
but songs from mods crash

**Comment by KarimAkra** [comment]
is the thing available on a public repo on github? i need to see smth to know if it's the issue
