### ISSUE TITLE
Recording Audio Won't Work 

### ISSUE THREAD

**Issue by RefuestJeremiah** [MobilePorting/FNF-PsychEngine-Mobile#137]
### Describe your bug here.

I tried to make a showcase but it comes out with no audio
But I am using 6.3

### Crash Log or logcat logs (if existing)

```bash
No Crash Logs
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I just recorded audio then when i went to watch it theres no audio

**Comment by KarimAkra** [comment]
We ported 0.7, 0.7.3 and 1.0b
We don't have anything to do With 0.6.3 so it isn't our issue nor we know anything about fixing it
