### ISSUE TITLE
Hold note

### ISSUE THREAD

**Issue by Sonk998** [MobilePorting/FNF-PsychEngine-Mobile#139]
### Describe your problem here.

I'm having trouble figuring out how to add a long/hold note when charting. Ik on PC u hold shift I believe but how do u do that on mobile?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by moxie-coder** [comment]
try tapping and holding

**Comment by Sonk998** [comment]
> try tapping and holding

Doesn't work

**Comment by KarimAkra** [comment]
You hold a button (G iirc?) then presse down
If that dosen't work just go to the note section in the editor UI and press +/- on the sustain length box

**Comment by Drago-Cuven** [comment]
wish the android version would be compatable with keyboards. bluetooth keyboards and USB to USB-C exists.

**Comment by KarimAkra** [comment]
it is compatible with keyboard
if your keyboard dosen't work with the game then it's ur phone's issue

**Comment by KarimAkra** [comment]
closing this for no response

**Comment by Drago-Cuven** [comment]
> it is compatible with keyboard if your keyboard dosen't work with the game then it's ur phone's issue

i'm on a Chromebook. i highly doubt that's the issue.

**Comment by KarimAkra** [comment]
Well
Either lime or android most of the time detects a keyboard as a gamepad
The game probably thinks you're using a gamepad because of that so the keybinds breaks
We can't really do anything about this sorry
