### ISSUE TITLE
Broken haxe/lua compatability

### ISSUE THREAD

**Issue by Drago-Cuven** [MobilePorting/FNF-PsychEngine-Mobile#140]
### Describe your bug here.

some mods that use advanced lua or haxe end up just giving a bunch of errors when applied or just crashing altogether.

such as ballistic in the 2BRemixed psych engine port (lua issue), and the [weekend1 Util mod]. (haxe issue)(https://discord.com/channels/922849922175340586/1236522550142701618/1244344321906442383)

[2024-05-25-10'48'27.txt](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/files/15484678/2024-05-25-10.48.27.txt)
[2024-05-25-10'07'57.txt](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/files/15484680/2024-05-25-10.07.57.txt)
[2024-05-25-09'51'17.txt](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/files/15484681/2024-05-25-09.51.17.txt)
[2024-05-13-07'12'01.txt](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/files/15484682/2024-05-13-07.12.01.txt)

### Crash Log or logcat logs (if existing)

```bash
uploaded crash log files.
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Other/Unknown/I don't know

### Did you edit anything in this build? If so, mention or summarize your changes.

no. i added the mods without any modification.

**Comment by Drago-Cuven** [comment]
> it's probably due SScript's discontinuation, they fucked it so we may needed downgrade SScript and do new devbuild release

understood.

**Comment by Drago-Cuven** [comment]
> it's probably due SScript's discontinuation, they fucked it so we may needed downgrade SScript and do new devbuild release

is it still going to happen?

**Comment by Stefan2008Git** [comment]
> > it's probably due SScript's discontinuation, they fucked it so we may needed downgrade SScript and do new devbuild release
> 
> is it still going to happen?

Maybe?

**Comment by Drago-Cuven** [comment]
![image](https://github.com/MobilePorting/FNF-PsychEngine-Base-Mobile/assets/57764393/1194dfcf-2b82-4612-9de3-769282bacb95)


> > > it's probably due SScript's discontinuation, they fucked it so we may needed downgrade SScript and do new devbuild release
> > 
> > 
> > is it still going to happen?
> 
> Maybe?

**Comment by Drago-Cuven** [comment]
still broken T-T

**Comment by Drago-Cuven** [comment]
I did redownload it just today btw

**Comment by Drago-Cuven** [comment]
still broken

**Comment by Drago-Cuven** [comment]
@mcagabe19 ?

**Comment by Drago-Cuven** [comment]
ok turns out its more broken than before. the [overworld script](https://gamebanana.com/tools/15947) that worked fine before now crashes psych when starting a song from it.

**Comment by mcagabe19** [comment]
maybe not compatiable script we tested mmv2 mods port, it works fine to us
