### ISSUE TITLE
Camara zooms bug

### ISSUE THREAD

**Issue by AStupidPersonXd123** [MobilePorting/FNF-PsychEngine-Mobile#141]
### Describe your bug here.

https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/166671910/297b6292-5872-4704-9fef-730a169a91cf

### Crash Log or logcat logs (if existing)

```bash
The event: function onEvent(name, value1, value2)
    if name == "Cam Zoom" then
        if value2 == nil or value2 == '' then
			setProperty('defaultCamZoom', tonumber(value1))
		else
            doTweenZoom('camZoom','camGame', tonumber(value1), tonumber(value2), 'sineInOut')
		end    
    end
end

function onTweenCompleted(name)
	if name == 'camZoom' then
		setProperty("defaultCamZoom", getProperty('camGame.zoom')) 
	end
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by moxie-coder** [comment]
that’s an issue with your script, not the game

**Comment by AStupidPersonXd123** [comment]
solve it for new players, or veterans, too. You can pass the code from 7.3 of the functions with scripts, and custom events but

**Comment by AStupidPersonXd123** [comment]
# make close

**Comment by AStupidPersonXd123** [comment]
# NO BAN ME PLS 🥺

**Comment by moxie-coder** [comment]
> solve it for new players, or veterans, too. You can pass the code from 7.3 of the functions with scripts, and custom events but I will play other versions

buddy wtf does this have to do with the problem?

**Comment by AStupidPersonXd123** [comment]
# brother, how stupid I am, I just should have installed another version 😵‍💫🤯

**Comment by AStupidPersonXd123** [comment]
the characters also get bugged
