### ISSUE TITLE
Long loading

### ISSUE THREAD

**Issue by GhostL650** [MobilePorting/FNF-PsychEngine-Mobile#17]
### Describe your bug here.

I go to freeplay and is loading for 30 seconds
The song like ugh is loading for 1 minute
Please fix this

### Crash Log or logcat logs (if existing)

```bash
No
```

### Are you modding a build from source or with Lua?

Lua

### What is your build 

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
Linux or Windows? I needed know that

**Comment by mcagabe19** [comment]
I mean did you build our psych for windows or limux?

**Comment by GhostL650** [comment]
> I mean did you build our psych for windows or linux? we didn't test desktop

No i didn't write that it's an android

**Comment by mcagabe19** [comment]
then probably low end device issue we can't do anything with it 🤷‍♀️
