### ISSUE TITLE
What is this error

### ISSUE THREAD

**Issue by pradolionel** [MobilePorting/FNF-PsychEngine-Mobile#176]
### Describe your problem here.

![Screenshot_20240819_225549](https://github.com/user-attachments/assets/0b67d151-c969-462d-bebb-2fc6fb34b826)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

### Which psych engine version you're on?

1.0 (Prerelease)

**Comment by mcagabe19** [comment]
seems unreleated idk

**Comment by brusakas** [comment]
https://lime.openfl.org/docs/advanced-setup/android/
just read this and you'll get it (read manuall install)
