### ISSUE TITLE
Character Editor Crash

### ISSUE THREAD

**Issue by Azedarkdragon** [MobilePorting/FNF-PsychEngine-Mobile#18]
### Describe your bug here.

Character editor crashes whenever I try to enter it

### Crash Log or logcat logs (if existing)

Null Object Reference
flixel/addons/ui/FlxUIDropDownMenu.hx (line 342)
states/editors/CharacterEditorState.hx (line 1067)
states/editors/CharacterEditorState.hx (line 437)
states/editors/CharacterEditorState.hx (line 191)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MemeHovy** [comment]
are you using the latest actions build?
