### ISSUE TITLE
Freaked up Cameras

### ISSUE THREAD

**Issue by Mike20242** [MobilePorting/FNF-PsychEngine-Mobile#182]
### Describe your bug here.

The game camera goes coo coo crazy
https://github.com/user-attachments/assets/f4f9d6c0-6967-4b2a-a4c6-d06a6178478a

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Which psych engine version you're on?

1.0 (Prerelease)

### Did you edit anything in this build? If so, mention or summarize your changes.

I haven't done anything

**Comment by moxie-coder** [comment]
this just seems like intentional behavior from the mods, there may be some cases where the scripts aren't compatible with 0.7/1.0, but otherwise this seems perfectly fine, this is just fucking stupid of you
