### ISSUE TITLE
Colored Bullets and Crash notes

### ISSUE THREAD

**Issue by Yo1239** [MobilePorting/FNF-PsychEngine-Mobile#19]
### Describe your bug here.

Some of them are colored bullets and the crash notes are not there

### Crash Log or logcat logs (if existing)

```bash
Nothing
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Desktop (Linux or Windows)

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MemeHovy** [comment]
this has got to be the most worst issue I've seen yet
