### ISSUE TITLE
How do I fix black textures?

### ISSUE THREAD

**Issue by TopedGames** [MobilePorting/FNF-PsychEngine-Mobile#195]
### What is your question?

— Video and additional information:
Engine version: DevBuild 2e5cd1d
![Screenshot_2024-09-08-23-20-10-10_1b0813e039defa1202c7e7c77137d1c1](https://github.com/user-attachments/assets/ecb15fef-7cb0-436b-a181-441a18a934c3)
![Screenshot_2024-09-08-23-20-02-19_1b0813e039defa1202c7e7c77137d1c1](https://github.com/user-attachments/assets/7af4be6c-b249-4b26-99df-11f7000c70a8)
![Screenshot_2024-09-08-23-19-58-29_1b0813e039defa1202c7e7c77137d1c1](https://github.com/user-attachments/assets/edc6425f-313e-4c83-b1db-b58f59562629)
https://github.com/user-attachments/assets/baf60807-2ed6-4bab-b22d-3c35396ee25e

**Comment by moxie-coder** [comment]
it’s an issue with your phones ram, and don’t open duplicate issues
