### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by Jose6304** [MobilePorting/FNF-PsychEngine-Mobile#202]
### What is your question?

When I try to launch the game it shows back when I leave and come back it say I don’t have files to run the game

**Comment by mcagabe19** [comment]
that's weird, that's probably your issue can't do anything

**Comment by WayloFunk** [comment]
Try manually extracting the assets from the android apk and add a logs folder too

**Comment by WayloFunk** [comment]
(I had the same problem on iOS)
