### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by EthanMG228** [MobilePorting/FNF-PsychEngine-Mobile#207]
### What is your question?

![whatthe](https://github.com/user-attachments/assets/5c301d27-1f23-427d-bd2c-97bb3d10fba4)
why is it not compiling?

**Comment by mcagabe19** [comment]
I'd rather to u use https://github.com/FunkinExtraKeys/FNF-PsychEngine-EK/tree/ek-mobile
