### ISSUE TITLE
It doesn't work at all!

### ISSUE THREAD

**Issue by Jahwsome** [MobilePorting/FNF-PsychEngine-Mobile#208]
### Describe your problem here.

Even if I have the .PsychEngine folder with hidden files on and everything, it still says that I have to create it!!!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Which psych engine version you're on?

0.7.3

**Comment by mcagabe19** [comment]
0.7.x is outdated, use 1.0 or devbuilds
