### ISSUE TITLE
Error! [openfl.display.Shader] ERROR: Error compiling fragment shader 0:133: S0001: Cannot compare 'int' with 'float' #ifdef GL_ES #ifdef GL_FRAGMENT_PRECISION_HIGH precision highp float; #else precision mediump float; #endif #endif varying float openfl_Alphav; varying vec4 openfl_ColorMultiplierv; varying vec4 openfl_ColorOffsetv; varying vec2 openfl_TextureCoordv;

### ISSUE THREAD

**Issue by DEEOXI** [MobilePorting/FNF-PsychEngine-Mobile#210]
### Describe your bug here.

Basically when i select any song in psych engime 0.7.3 on mobile i get this error
![Screenshot_20241013_134916](https://github.com/user-attachments/assets/65c8486c-2935-4d11-b3b0-23a37a8ad246)

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Which psych engine version you're on?

0.7.3

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
there's an int that should be float check if u have (number). if so make it (number).0
