### ISSUE TITLE
Mods incompatibility.

### ISSUE THREAD

**Issue by accidentallyagoober** [MobilePorting/FNF-PsychEngine-Mobile#213]
### Describe your bug here.

Every mod I had from 0.7.3, except reskin mods, don't work in the 1.0 version. Some of them make the game crash without logging anything, and other's just straight up don't do anything. I think it might be something with the scripts but I can't seem to recognize anythin wrong

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Which psych engine version you're on?

1.0 (Final)

### Did you edit anything in this build? If so, mention or summarize your changes.

Not at all. I played it in the default settings but with 0.7.3 script mods active.

**Comment by mcagabe19** [comment]
upstream issue
