### ISSUE TITLE
It says I’m missing some files

### ISSUE THREAD

**Issue by Zeakseafan** [MobilePorting/FNF-PsychEngine-Mobile#214]
### Describe your bug here.

I don’t know what happened because it’s an ipa file I imported to AltStore. I clicked ok to begin the a file copy process but the button doesn’t appear to work.

https://github.com/user-attachments/assets/fac4f60c-183d-427d-a36b-b03f95fceffd

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

iOS

### Which psych engine version you're on?

1.0 (Final)

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by Zeakseafan** [comment]
Did I do something wrong?

**Comment by Zeakseafan** [comment]
Im also new

**Comment by Zeakseafan** [comment]
Im new here breh.

**Comment by Zeakseafan** [comment]
E

**Comment by moxie-coder** [comment]
stop opening and closing the issue

**Comment by moxie-coder** [comment]
also it would be nice if you had some fucking patience

**Comment by Zeakseafan** [comment]
> also it would be nice if you had some fucking patience you annoying ass kid

Lmao

**Comment by Zeakseafan** [comment]
> > also it would be nice if you had some fucking patience you annoying ass kid
> 
> Lmao

Shiver me Timbers bro😭

**Comment by moxie-coder** [comment]
you know what? I've got a better solution for you

**Comment by tposejank** [comment]
![Screenshot_20241017_082905_Brave](https://github.com/user-attachments/assets/58ea804a-fedf-4b9c-9470-da63bfef1e27)
