### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by Mirko2893** [MobilePorting/FNF-PsychEngine-Mobile#216]
### Describe your bug here.

When a cutscene ends (Like Weekend 1) the Screen is black and don't start the song

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Which psych engine version you're on?

1.0 (Final)

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i did not edit anything

**Comment by JacksonTheSkylanderDude67** [comment]
@mcagabe19 if mine was a duplicate did you at least fix the issue?

**Comment by mcagabe19** [comment]
closing as not planned cuz we don't know
