### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by Tacorandomguy** [MobilePorting/FNF-PsychEngine-Mobile#217]
Black screen

When I installed the port i tried opening it and it says on a black screen for minutes and when I exit the app it and wait a bit in go back in it says I’m missing some files and when it says to press ok to create copy it won’t let me press it please help me fix this problem
![IMG_1027](https://github.com/user-attachments/assets/c8f3fd71-22d6-4cd7-8d38-34c66356eb9b)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

iOS

### Which psych engine version you're on?

1.0 (Final)

### Did you edit anything in this build? If so, mention or summarize your changes.

No I didn’t just installed it

**Comment by mcagabe19** [comment]
should be fixed, redonwload the release
