### ISSUE TITLE
IOS Verify Error

### ISSUE THREAD

**Issue by 12345keddie** [MobilePorting/FNF-PsychEngine-Mobile#218]
### Describe your problem here.

I Downloaded The IPA File And Put It On My iPhone. When I Opened It, An Error Message Popped Up Saying, "Unable to Install Friday Night Funkin': Psych Engine." This app cannot be installed because its integrity could not be verified." 

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

iOS

### Which psych engine version you're on?

1.0 (Final)

**Comment by mcagabe19** [comment]
scarlet is taken down yet again, use altserver with pc

**Comment by mcagabe19** [comment]
and if u have scarlet working, learn how to enable developer mode in ur iPhone

**Comment by 12345keddie** [comment]
I Can't Do Either

**Comment by mcagabe19** [comment]
nothing I can do about it
