### ISSUE TITLE
Controls are messed up.

### ISSUE THREAD

**Issue by DoubbleTheFun** [MobilePorting/FNF-PsychEngine-Mobile#219]
### Describe your bug here.

The controls have been messed up by the 1.0 update.

In the menu:
Every button other then E appears to do either nothing, or the wrong thing. For isntance, Up is A, Down is Z, Left and Right appear to do nothing, and I can't figure out what ABXY do.

In game:
Left = Down
Down = Up
Up = Nothing
Right = Left

I even tried having the game re-download assets, and eventually reinstalling, and the issue persists.

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Which psych engine version you're on?

1.0 (Final)

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by mcagabe19** [comment]
fully reinstall
