### ISSUE TITLE
Game doesn't open

### ISSUE THREAD

**Issue by NuggetSus** [MobilePorting/FNF-PsychEngine-Mobile#22]
### Describe your problem here.

When i put the assets and mods folder in the .PsychEngine the game doesn't open, maybe i'm doing something wrong

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

**Comment by mcagabe19** [comment]
which release you downloaded?

**Comment by NuggetSus** [comment]
The last one released, the last one has the same problem as well

**Comment by mcagabe19** [comment]
I have to look at that

**Comment by NuggetSus** [comment]
Ok, thanks for answering

**Comment by mcagabe19** [comment]
@NuggetSus can u try [that build](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/actions/runs/6024517481)? (download androidBuild-gcc-EXTERNAL)

**Comment by NuggetSus** [comment]
Sure

**Comment by NuggetSus** [comment]
It didn't work

**Comment by mcagabe19** [comment]
hmm

**Comment by mcagabe19** [comment]
we totally have issues at .PsychEngine and we will try fix that so we gonna use Android/data for now.
