### ISSUE TITLE
Android touch controls doesn't work good

### ISSUE THREAD

**Issue by Kodrikz64** [MobilePorting/FNF-PsychEngine-Mobile#220]
### Describe your bug here.

I Dont know how i can explain this, just watch...
(this also happens in song selector) 

https://github.com/user-attachments/assets/ae358457-d7b6-48d4-994c-2dcc387bd2f7

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Which psych engine version you're on?

1.0 (Final)

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i didn't, i even reinstalled every goddamn file

**Comment by mcagabe19** [comment]
fully reinstall
