### ISSUE TITLE
The buttons don't work

### ISSUE THREAD

**Issue by TwisBbbb** [MobilePorting/FNF-PsychEngine-Mobile#221]
### Describe your bug here.

Help, my psych engine doesn't work, the buttons just press and don't perform their functions

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Which psych engine version you're on?

1.0 (Final)

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
fully reinstall
