### ISSUE TITLE
The buttons don't work 

### ISSUE THREAD

**Issue by TwisBbbb** [MobilePorting/FNF-PsychEngine-Mobile#222]
### Describe your bug here.

I completely reinstalled the game 5 times, the buttons don't work  . Don't ignore the bug!!!

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Which psych engine version you're on?

1.0 (Final)

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
that is no sense issue, that is a you issue
