### ISSUE TITLE
Stages.json with images

### ISSUE THREAD

**Issue by JuanSebas1247** [MobilePorting/FNF-PsychEngine-Mobile#224]
### Describe your problem here.

So the stage editor does not allow adding images or animated sprites in mobile, could someone pass some JSON with an example image, it does not matter which one, just that it has the values of the Images since I don't have a PC to try it and I would like to test how it works XD

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Which psych engine version you're on?

1.0 (Final)

**Comment by mcagabe19** [comment]
stage editor not "officially" supported for mobile actually
