### ISSUE TITLE
Controls aren't working as intended 

### ISSUE THREAD

**Issue by MyNamesDJ** [MobilePorting/FNF-PsychEngine-Mobile#226]
### Describe your bug here.

Basically, the controls aren't working properly. The up button makes you go back, the down button makes you proceed, and left, right, A, and B do nothing. I can't change my key binds to fix this issue, as I demonstrated why in the following clip:

https://github.com/user-attachments/assets/a02734a0-6b37-4e25-bf11-0199b2dc3ff7

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Which psych engine version you're on?

1.0 (Final)

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing was edited, as I was physically unable to.

**Comment by mcagabe19** [comment]
clear data

**Comment by MyNamesDJ** [comment]
@mcagabe19 Same issue is still present. I tried clearing my data, and it didn't work. I even tried to uninstall and reinstall the game, and the controls still don't work properly

**Comment by mcagabe19** [comment]
that's still a you issue, we don't have that issue consider using devbuild's instead
