### ISSUE TITLE
Sprite's graphics being placed way too high

### ISSUE THREAD

**Issue by RichardEdu114** [MobilePorting/FNF-PsychEngine-Mobile#227]
### Describe your bug here.

For some reason sprites graphics are placed way too high or do not appear when using addLuaSprite even though sprites appear normally if placed at onCreate function and their position is actually on the original position

SpriteY = original first cloud layer y position
CopyY = same as above but for the copy

https://github.com/user-attachments/assets/9ebf781e-1a33-4568-a2a5-a710ebbe6043

Code (incase its needed):
backgroundGroup = {'clouds1', 'clouds2', 'clouds3', 'mountains1', 'mountains2', 'water'} --Tags of all the background pieces
cloudsVelTable = {0.7, 0.5, 0.2} --Velocity that all clouds automatically scroll
function onCreate()
    --The entire background
	makeLuaSprite('clouds1', 'Sonic 1 Assets/Stages/GHZ/strip1', 0, 0);
	setScrollFactor('clouds1', 1, 1);
    scaleObject('clouds1', 1.0, 1.0);
    setProperty('clouds1.antialiasing', false)
    
	makeLuaSprite('clouds2', 'Sonic 1 Assets/Stages/GHZ/strip2', 0, 32);
	setScrollFactor('clouds2', 1, 1);
	scaleObject('clouds2', 1.0, 1.0);
    setProperty('clouds2.antialiasing', false)
    
	makeLuaSprite('clouds3', 'Sonic 1 Assets/Stages/GHZ/strip3', 0, 48);
	setScrollFactor('clouds3', 1, 1)
    scaleObject('clouds3', 1.0, 1.0);
	setProperty('clouds3.antialiasing', false)
	
	makeLuaSprite('mountains1', 'Sonic 1 Assets/Stages/GHZ/strip4', 0, 64);
	setScrollFactor('mountains1', 0.4, 1);
	scaleObject('mountains1', 1, 1);
	setProperty('mountains1.antialiasing', false)
	
	makeLuaSprite('mountains2', 'Sonic 1 Assets/Stages/GHZ/strip5', 0, 112);
	setScrollFactor('mountains2', 0.6, 1);
	scaleObject('mountains2', 1, 1);
	setProperty('mountains2.antialiasing', false)
	
	makeLuaSprite('water', 'Sonic 1 Assets/Stages/GHZ/strip6', 0, 152);
	setScrollFactor('water', 0.8, 1);
	scaleObject('water', 1, 1);
	setProperty('water.antialiasing', false)
	
	addLuaSprite('clouds1', false);
	addLuaSprite('clouds2', false);
	addLuaSprite('clouds3', false);	
	addLuaSprite('mountains1', false);
	addLuaSprite('mountains2', false);
	addLuaSprite('water', false)
end
function onUpdate()
   for i = 1, 3 do --look for 3 pieces of the background group
   setProperty(backgroundGroup[i] .. '.x', getProperty(backgroundGroup[i].. '.x') - cloudsVelTable[i]) -- subtract the position of the cloud with the number seen in the cloud table to move the clouds
   end
   updateParallax() --Function that deals with parallax (mainly the clouds)
 end
 function updateParallax()
 for i = 1, #backgroundGroup do --look for all backgrounds in the table (this is made that way because of another thing)
   if getProperty(backgroundGroup[i] .. '.x') + getProperty(backgroundGroup[i] .. '.width') <= getCameraScrollX() + screenWidth / 2 and not dontRemake then --look to see if the background has scrolled enough
      makeLuaSprite(backgroundGroup[i] .. 'lol', 'Sonic 1 Assets/Stages/GHZ/strip' .. i, getProperty(backgroundGroup[i] .. '.x') + getProperty(backgroundGroup[i] .. '.width'), getProperty(backgroundGroup[i]..'.y')) --create a copy of an background layer
      setScrollFactor(backgroundGroup[i] .. 'lol', backgroundGroup[i] .. '.scrollFactor.x', backgroundGroup[i] .. '.scrollFactor.y'); --copy the scroll factor
      setProperty(backgroundGroup[i] .. 'lol.antialiasing', false) --remove antialiasing
      addLuaSprite(backgroundGroup[i] .. 'lol', false) --add the backgroud piece
      end
         if luaSpriteExists(backgroundGroup[i] .. 'lol') then -- if the background layer exists
         --debugPrint('spriteY:' .. getProperty('clouds1.y') ..  ' copyY:' .. getProperty('clouds1lol.x'))
            if getProperty(backgroundGroup[i] .. 'lol.x') <= getCameraScrollX() - screenWidth / 2 then -- if background has scrolled enough
            setProperty(backgroundGroup[i] .. '.x', getProperty(backgroundGroup[i] .. 'lol.x')) --set the original background piece to be in the same position as the copy
            removeLuaSprite(backgroundGroup[i] .. 'lol', true) --delete the copied background piece
            end
         end
         end
 end

### Crash Log or logcat logs (if existing)

```bash
No Response
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Which psych engine version you're on?

DevBuild

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
upstream issue
