### ISSUE TITLE
Scrolling Issue in Character and Chart Editors

### ISSUE THREAD

**Issue by Contra-Sakar** [MobilePorting/FNF-PsychEngine-Mobile#228]
### Describe your bug here.

This error was already mentioned by someone else before, where they said that it's not possible to scroll up or down in the character editor when trying to select a character. This also happens with the chart editor, and the issue becomes even more annoying when you have many events, as searching for each one by typing is bothersome. This also occurs with the P-Slice Engine.

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Which psych engine version you're on?

1.0 (Final)

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
drop down's doesn't have scrolling, you have to search by its name

**Comment by Contra-Sakar** [comment]
The previous person who mentioned this error
https://github.com/MobilePorting/FNF-PsychEngine-Mobile/issues/205

**Comment by mcagabe19** [comment]
> drop down's doesn't have scrolling, you have to search by its name

^
