### ISSUE TITLE
Extra mobile controls together (not the hitbox ones)

### ISSUE THREAD

**Issue by Miguelpescript** [MobilePorting/FNF-PsychEngine-Mobile#23]
### Describe your bug here.

Nothing to explain much, is because J and G extra buttons are fused, i allredy tried move these on mobile controls menu, some way to fix it?

### Crash Log or logcat logs (if existing)

```bash
No crash log
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by Karim-Akra** [comment]
idk why that suddenly happend but like... set the extra buttons to one, move a button then go back and set them to two so you can move the scond button for now until i fix it

**Comment by Miguelpescript** [comment]
Oh it worked

**Comment by Miguelpescript** [comment]
Thanks 👍

**Comment by Miguelpescript** [comment]
One more thing, how the buttons are called on the code?
Like:
   If getProperty('GbuttonPress.OrSomethingLikeThat') then

**Comment by Karim-Akra** [comment]
if extraButtonPressed('first') or if extraButtonPressed('second')

i don't remember which one is which tho sorry but these are for both virtual pad and hitbox

**Comment by Miguelpescript** [comment]
Ok, should i close this? Or you close?
