### ISSUE TITLE
Weekend 1 Freeze after Cutscene android 1.0

### ISSUE THREAD

**Issue by epicmdj** [MobilePorting/FNF-PsychEngine-Mobile#230]
### Describe your bug here.

Weekend 1 in story mode after cutscene just freezes, any fixes? Android 1.0

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Which psych engine version you're on?

1.0 (Final)

### Did you edit anything in this build? If so, mention or summarize your changes.

Not related

**Comment by moxie-coder** [comment]
duplicate of #223
