### ISSUE TITLE
Custom fonts don't display the custom font even with setTextFont function 

### ISSUE THREAD

**Issue by RichardEdu114** [MobilePorting/FNF-PsychEngine-Mobile#232]
### Describe your bug here.

setTextFont dont work

https://github.com/user-attachments/assets/539a2072-d565-47a5-9e5e-3c5d2edecb54

### Crash Log or logcat logs (if existing)

```bash
No response
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Which psych engine version you're on?

DevBuild

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
use luaDebugMode and check what it says

**Comment by RichardEdu114** [comment]
> use luaDebugMode and check what it says
I was already using lua debug mode and said nothing

**Comment by RichardEdu114** [comment]
Same with getTextFont

**Comment by mcagabe19** [comment]
is this issue still persists on latest devbuild

**Comment by RichardEdu114** [comment]
Nope

**Comment by RichardEdu114** [comment]
Is fixed now

**Comment by mcagabe19** [comment]
if it's fixed closing as resolved
