### ISSUE TITLE
I have a problem with my fire shader..

### ISSUE THREAD

**Issue by softbf395** [MobilePorting/FNF-PsychEngine-Mobile#233]
oops, I accidentally got the issue type wrong
### What is your question?
Crash log:
`no response`
I’m making a lua game (basically like an overworld mod, except it’s a game where u shoot enemies in space) in psych engine iOS, impossible mode will have a fire shader, but it crashes every time I play impossible mode, current frag code:
#pragma header
vec2 fragCoord = openfl_TextureCoordv*openfl_TextureSize;
vec2 iResolution = openfl_TextureSize;
uniform float iTime;
#define iChannel0 bitmap
#define texture texture2D
#define fragColor gl_FragColor
#define mainImage main 

float noise(vec2 p) {
    return fract(sin(dot(p, vec2(12.9898, 78.233))) * 43758.5453);
}

void mainImage(out vec4 fragColor) {
    vec2 uv = fragCoord.xy / iResolution.xy;

    // Calculate fire intensity based on distance from bottom of the screen and noise
    float fireIntensity = 1.0 - uv.y + noise(uv * 10.0 + iTime * 0.5) * 0.2;

    // Create a fire color gradient with noise-based variations
    vec3 fireColor = mix(vec3(1.0, 0.5, 0.0), vec3(1.0, 0.0, 0.0), fireIntensity);
    fireColor += noise(uv * 5.0 + iTime) * 0.1;

    // Introduce turbulence and heat distortion
    vec2 distortedUV = uv + noise(uv * 5.0 + iTime * 0.5) * 0.02;

    // Teleportation effect
    if (distortedUV.y > 1.0) {
        distortedUV.y -= 1.0;
    }

    // Sample the texture (replace with your actual texture if needed)
    vec4 color = texture2D(bitmap, distortedUV);

    // Combine fire color with texture and apply alpha
    fragColor = vec4(fireColor * color.rgb, 1.0 - fireIntensity * 0.5);
}

**Comment by softbf395** [comment]
Also there’s no LOG files built by it, also wrong section for issue

**Comment by softbf395** [comment]
Also there’s no LOG files built by it, also wrong section for issue

**Comment by softbf395** [comment]
Incase your wondering, green is player, cyan is bullets, red is enemies, the squares are placeholder graphics
![IMG_4144](https://github.com/user-attachments/assets/74479b62-cb58-4797-83da-40416515202b)
The button in the top left is to exit because on mobile you can’t use keys to exit the level

**Comment by softbf395** [comment]
There’s a compile error even if I tried
#pragma header
vec2 fragCoord = openfl_TextureCoordv * openfl_TextureSize;
vec2 iResolution = openfl_TextureSize;
uniform float iTime;
#define iChannel0 bitmap
#define   
 texture texture2D
#define FragColor gl_FragColor
#define mainImage main

// Precomputed noise texture (optional)
uniform sampler2D noiseTexture;

float noise(vec2 p) {
    // Consider using a precomputed noise texture for better performance
    return texture2D(noiseTexture, p).r;
}

void mainImage() {
    vec2 uv = fragCoord.xy / iResolution.xy;

    // Simplified fire intensity calculation
    float fireIntensity = clamp(1.0 - uv.y, 0.0, 1.0);

    // Precomputed fire color gradient (optional)
    vec3 fireColor = mix(vec3(1.0, 0.5, 0.0), vec3(1.0, 0.0, 0.0), fireIntensity);
    fireColor += noise(uv * 5.0 + iTime) * 0.1;

    // Introduce turbulence and heat distortion
    vec2 distortedUV = uv + noise(uv * 5.0 + iTime * 0.5) * 0.02;

    // Teleportation effect (optional)
    // if (distortedUV.y > 1.0) {
    //     distortedUV.y -= 1.0;
    // }

    // Sample the texture (replace with your actual texture if needed)
    vec4 textureColor = texture2D(bitmap, distortedUV);

    // Combine fire color with texture color and apply alpha
    FragColor = vec4(fireColor * textureColor.rgb, textureColor.a);
}
Compile error:
Error compiling fragment shader
ERROR: 0:91: Use of undeclared identifier 'FragColor'

#ifdef GL_ES
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif
#endif

varying float openfl_Alphav;
		varying vec4 openfl_ColorMultiplierv;
		varying vec4 openfl_ColorOffsetv;
		varying vec2 openfl_TextureCoordv;

		uniform bool openfl_HasColorTransform;
		uniform vec2 openfl_TextureSize;
		uniform sampler2D bitmap;

		uniform bool hasTransform;
		uniform bool hasColorTransform;

		vec4 flixel_texture2D(sampler2D bitmap, vec2 coord)
		{
			vec4 color = texture2D(bitmap, coord);

			if (!hasTransform)
			{
				return color;
			}

			if (color.a == 0.0)
			{
				return vec4(0.0, 0.0, 0.0, 0.0);
			}

			if (!hasColorTransform)
			{
				return color * openfl_Alphav;
			}

			color = vec4(color.rgb / color.a, color.a);

			mat4 colorMultiplier = mat4(0);
			colorMultiplier[0][0] = openfl_ColorMultiplierv.x;
			colorMultiplier[1][1] = openfl_ColorMultiplierv.y;
			colorMultiplier[2][2] = openfl_ColorMultiplierv.z;
			colorMultiplier[3][3] = openfl_ColorMultiplierv.w;

			color = clamp(openfl_ColorOffsetv + (color * colorMultiplier), 0.0, 1.0);

			if (color.a > 0.0)
			{
				return vec4(color.rgb * color.a * openfl_Alphav, color.a * openfl_Alphav);
			}

			return vec4(0.0, 0.0, 0.0, 0.0);
		}
vec2 fragCoord = openfl_TextureCoordv*openfl_TextureSize;
vec2 iResolution = openfl_TextureSize;
uniform float iTime;
#define iChannel0 bitmap
#define texture texture2D
#define fragColor FragColor
#define mainImage main

float noise(vec2 p) {
    return fract(sin(dot(p, vec2(12.9898, 78.233))) * 43758.5453);
}

void mainImage() {
    vec2 uv = fragCoord.xy / iResolution.xy;

    // Calculate fire intensity based on distance from bottom of the screen and noise
    float fireIntensity = 1.0 - uv.y + noise(uv * 10.0 + iTime * 0.5) * 0.2;

    // Create a fire color gradient with noise-based variations
    vec3 fireColor = mix(vec3(1.0, 0.5, 0.0), vec3(1.0, 0.0, 0.0), fireIntensity);
    fireColor += noise(uv * 5.0 + iTime) * 0.1;

    // Introduce turbulence and heat distortion
    vec2 distortedUV = uv + noise(uv * 5.0 + iTime * 0.5) * 0.02;

    // Teleportation effect
    if (distortedUV.y > 1.0) {
        distortedUV.y -= 1.0;
    }

    // Sample the texture (replace with your actual texture if needed)
    vec4 color = texture2D(bitmap, distortedUV);

    // Combine fire color with texture and apply alpha
    fragColor = vec4(fireColor * color.rgb, 1.0 - fireIntensity * 0.5);
}

**Comment by moxie-coder** [comment]
iOS has no shader support from what I know, I don’t know the logistics of it yet but this seems out of our scope

**Comment by mcagabe19** [comment]
this issue have no information at all
