### ISSUE TITLE
Button dont working

### ISSUE THREAD

**Issue by Amebusgus228** [MobilePorting/FNF-PsychEngine-Mobile#234]
### Describe your bug here.

I want make Stage but button no animated dont working :(

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Which psych engine version you're on?

1.0 (Final)

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i dont maked nothing

**Comment by mcagabe19** [comment]
use devbuilds instead with fully reinstall
