### ISSUE TITLE
How do you change your bindings on a controller?

### ISSUE THREAD

**Issue by TheArtistBehindYou** [MobilePorting/FNF-PsychEngine-Mobile#235]
### Describe your problem here.

I have no idea how to, I'm using a Nacon GX-Pro Xbox Controller and the 
Notes input, but I want to change the bindings.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

### Which psych engine version you're on?

DevBuild

**Comment by mcagabe19** [comment]
make your mobile controls opacity 0, goto controls and hold l2 or r2 to switch controller inputs

**Comment by TheArtistBehindYou** [comment]
Thanks.
