### ISSUE TITLE
I Failed Build Source Code

### ISSUE THREAD

**Issue by megalives717** [MobilePorting/FNF-PsychEngine-Mobile#236]
### Describe your problem here.

https://github.com/user-attachments/assets/c4eea186-6ab6-4eae-8ab8-436899b7d937

help

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Desktop (Linux, Windows or Mac)

### Which psych engine version you're on?

1.0 (Final)

**Comment by mcagabe19** [comment]
make sure you have correct library versions
https://github.com/MobilePorting/FNF-PsychEngine-Mobile/blob/c8716e5e75058a765847254f03e69461b8e5fc30/.github/workflows/build.yml#L55-L69

**Comment by megalives717** [comment]
not working

**Comment by mcagabe19** [comment]
what about this
https://github.com/MobilePorting/FNF-PsychEngine-Mobile/blob/da2a0c48e4c693641a2ade8ea77ff7c4d29141b1/.github/workflows/main.yml#L25-L38

**Comment by megalives717** [comment]
it's work thank you
