### ISSUE TITLE
lime not installing

### ISSUE THREAD

**Issue by megalives717** [MobilePorting/FNF-PsychEngine-Mobile#237]
### Describe your problem here.

i can't install lime in build.yml

https://github.com/user-attachments/assets/1e8b27b6-04fc-4f0c-8e0c-1d2555ba340c

help!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Desktop (Linux, Windows or Mac)

### Which psych engine version you're on?

1.0 (Final)

**Comment by moxie-coder** [comment]
that’s just visual studio setting up lime, just do `haxelib install lime`

**Comment by megalives717** [comment]
no

**Comment by megalives717** [comment]
i can't install git version of lime

**Comment by moxie-coder** [comment]
> i can't install git version of lime

then do ‘haxelib git lime https://github.com/mcagabe19-stuff/lime`

**Comment by moxie-coder** [comment]
> ![not fixed](https://private-user-images.githubusercontent.com/181967496/387200444-ee9079b8-4047-4f91-9720-8a8ba560df9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MzEwNTAsIm5iZiI6MTczMTkzMDc1MCwicGF0aCI6Ii8xODE5Njc0OTYvMzg3MjAwNDQ0LWVlOTA3OWI4LTQwNDctNGY5MS05NzIwLThhOGJhNTYwZGY5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQxMTUyMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODI2ZmNhZjk2ODcyM2MyM2I3ZGJjNjNlNDM4YjQ4NTVmNmIwMzdkZDM3YTY2ZjNjODYyNGUwMjY2YzI0ZDE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pZpWfhnHop1PoMG5-EpgWMRGwOyCn2PMbiH0Jo1p6zw) it's not installed thank you

then rerun he command
