### ISSUE TITLE
(Suggestion) Game Mode for iOS 17 and up

### ISSUE THREAD

**Issue by WayloFunk** [MobilePorting/FNF-PsychEngine-Mobile#239]
### What is your question?

It basically just makes the processor run more toward the game and Bluetooth connectivity by lowering resources used by background operations. When it does this, the ram split will be more toward the game too because of these extra processes get ended.

**Comment by WayloFunk** [comment]
This might help lol https://developer.apple.com/documentation/bundleresources/information-property-list/lsapplicationcategorytype?language=objc

Set this to games

**Comment by WayloFunk** [comment]
This would also help with the categorization on iOS

**Comment by moxie-coder** [comment]
already exists in Linux, and it does seem like a good idea, but idk how to implement it

**Comment by mcagabe19** [comment]
needs to be done on my lime I think
