### ISSUE TITLE
Using the phone's back button to exit something

### ISSUE THREAD

**Issue by JuanSebas1247** [MobilePorting/FNF-PsychEngine-Mobile#241]
### Describe your problem here.

I'm making a menu, and a port to Android of a mod, but I want to use Lua to make it exit the menu I made in Lua with the phone's backend, is that possible?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Which psych engine version you're on?

1.0 (Final)

**Comment by mcagabe19** [comment]
please look at https://github.com/MobilePorting/FNF-PsychEngine-Mobile/wiki/Mobile-Lua-API
