### ISSUE TITLE
Help, I am a little inexperienced.

### ISSUE THREAD

**Issue by NikkiUzira9715** [MobilePorting/FNF-PsychEngine-Mobile#26]
### Describe your problem here.

I am having a little trouble with getting the apk to open. Is there anything I need to do inorder to set the apk up on my end?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

**Comment by MemeHovy** [comment]
do you not know how to import a apk?

**Comment by benok99** [comment]
JIT LMAOO

**Comment by Karim-Akra** [comment]
Is it that hard to click a apk then install it?

**Comment by benok99** [comment]
"Little inexperienced" that's for sure

**Comment by NikkiUzira9715** [comment]
It keeps saying I have a conflicting file when I have literally nothing that it could conflict with.

**Comment by NikkiUzira9715** [comment]
So, I don't know if I am doing something wrong or if I need to do something else.

**Comment by NikkiUzira9715** [comment]
https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/141879210/35788cf9-6e28-447b-a76c-e4b1fa9b3a86

**Comment by NikkiUzira9715** [comment]
I have uninstalled it, reinstalled it, and cleared my apps cache. I have no idea what else to do.

**Comment by NikkiUzira9715** [comment]
@Karim-Akra @MemeHovy (sorry for the ping) (You two seem to have been the nicest, I've uploaded a video of what I mean. Any ideas of what I can try to do?)

**Comment by NikkiUzira9715** [comment]
Nvm, I had to restart my phone 💀

**Comment by Karim-Akra** [comment]
This problem happened with ke

**Comment by mcagabe19** [comment]
android 11 issue it doesn't deletes the shit u have so u have to factory reset phone or delete app from via adb/root

**Comment by Karim-Akra** [comment]
it's a general android issue it happend with me in android 7 and 6

**Comment by mcagabe19** [comment]
> it's a general android issue it happend with me in android 7 and 6

then we can't do anything it's android releated issue not from we

**Comment by MemeHovy** [comment]
![image](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/124418090/45d79b4f-2fbd-4280-b6ad-c1431f98d3e8)
don't close this as completed btw @mcagabe19

**Comment by NikkiUzira9715** [comment]
Turns out it was my bunzo bunny apk that was stopping it.
