### ISSUE TITLE
chromebook support

### ISSUE THREAD

**Issue by Drago-Cuven** [MobilePorting/FNF-PsychEngine-Mobile#35]
### What is your question?

Could you please add an update with chromebooks in mind? i can't use the charting menu and its a shame i can't get the menu buttons off.

**Comment by MemeHovy** [comment]
this is a mobile repo, not a chromebook repo, and plus chromebook is literally based on linux, why not just download a linux build of psych?

**Comment by Martinelplayz** [comment]
> this is a mobile repo, not a chromebook repo, and plus chromebook is literally based on linux, why not just download a linux build of psych?

Chromebooks are basically glorified android tablets and most "basic" chromebooks are not really that powerful nor do they have much memory. a $50 phone has more memory than the chromebook im on right now. that being said i'm pretty much incapable of actually using linux on this thing, and have to rely on android releases since by default THIS CHROMEBOOK IS ANDROID.

**Comment by MemeHovy** [comment]
> > this is a mobile repo, not a chromebook repo, and plus chromebook is literally based on linux, why not just download a linux build of psych?
> 
> Chromebooks are basically glorified android tablets and most "basic" chromebooks are not really that powerful nor do they have much memory. a $50 phone has more memory than the chromebook im on right now. that being said i'm pretty much incapable of actually using linux on this thing, and have to rely on android releases since by default CHROMEBOOKS AREANDROID.

the only thing I can think of is to reduce the quality, like turn low quality mode on and such, we can't do much about low end devices really and they're hard to detect in haxe/flixel. Maybe in the future I can add more optimization options but uh for now, this is all I can say really because there's not much that can be done about it other then changing settings.

**Comment by Martinelplayz** [comment]
> > > this is a mobile repo, not a chromebook repo, and plus chromebook is literally based on linux, why not just download a linux build of psych?
> > 
> > 
> > Chromebooks are basically glorified android tablets and most "basic" chromebooks are not really that powerful nor do they have much memory. a $50 phone has more memory than the chromebook im on right now. that being said i'm pretty much incapable of actually using linux on this thing, and have to rely on android releases since by default CHROMEBOOKS AREANDROID.
> 
> the only thing I can think of is to reduce the quality, like turn low quality mode on and such, we can't do much about low end devices really and they're hard to detect in haxe/flixel. Maybe in the future I can add more optimization options but uh for now, this is all I can say really because there's not much that can be done about it other then changing settings.

literally all i'm asking for is the ability to disable mobile controls as a whole.

**Comment by Martinelplayz** [comment]
mainly in the charting menu

**Comment by MemeHovy** [comment]
oh okay, sure thing

**Comment by mcagabe19** [comment]
will look one day

**Comment by mcagabe19** [comment]
but @Martinelplayz u have to show what is your architecture

**Comment by Martinelplayz** [comment]
> but @Martinelplayz u have to show what is your architecture (uname -m in every terminal)

? not sure exactly what you mean by that.

**Comment by mcagabe19** [comment]
> > but @Martinelplayz u have to show what is your architecture (uname -m in every terminal)
> 
> ? not sure exactly what you mean by that.

install a terminal to your chromebook and write ``uname -m``

**Comment by mcagabe19** [comment]
ur chromebook can simulate arm64? (did u tried our builds before?)

**Comment by mcagabe19** [comment]
and @Martinelplayz u can just go options -> Mobile Controls and change opacity to 0

**Comment by Martinelplayz** [comment]
> and @Martinelplayz u can just go options -> Mobile Controls and change opacity to 0

i can't even use the chart editor because of it though and i can't set opacity to 0. it won't let me set it that low.

**Comment by Martinelplayz** [comment]
i was the charter for the [margherita mix](https://gamebanana.com/mods/319779) mod and currently the co-director, charter and programmer for the [Friday night animators](https://gamebanana.com/mods/360446) mod. so i DO need to make use of the chart editor and the fact that either the mobile buttons are in the way or keyboard and mouse controls for that menu was removed, i can't even use it.

**Comment by KarimAkra** [comment]
> > and @Martinelplayz u can just go options -> Mobile Controls and change opacity to 0
> 
> i can't even use the chart editor because of it though and i can't set opacity to 0. it won't let me set it that low.

You're using an old build that has a 29
