### ISSUE TITLE
What happened to me?

### ISSUE THREAD

**Issue by Euro55222** [MobilePorting/FNF-PsychEngine-Mobile#36]
### Describe your problem here.

source/SUtil.hx:5: characters 8-31 : Type not found : android.content.Context

source/SUtil.hx:7: characters 8-28 : Type not found : android.widget.Toast
source/SUtil.hx:8: characters 8-30 : Type not found : android.os.Environment
source/SUtil.hx:52: characters 14-21 : Type not found : Context
source/SUtil.hx:54: characters 14-21 : Type not found : Context
source/SUtil.hx:56: characters 14-25 : Type not found : Environment
source/SUtil.hx:58: characters 14-25 : Type not found : Environment
source/SUtil.hx:168: characters 4-9 : Type not found : Toast
source/SUtil.hx:80: characters 65-87 : Class<android.Permissions> has no field WRITE_EXTERNAL_STORAGE
source/SUtil.hx:81: characters 65-86 : Class<android.Permissions> has no field READ_EXTERNAL_STORAGE
source/SUtil.hx:83: characters 8-23 : Type not found : VERSION
source/SUtil.hx:249: characters 4-9 : Type not found : Toast
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/text/FlxTypeText.hx:8: characters 8-29 : Type not found : flixel.sound.FlxSound
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/text/FlxTypeText.hx:78: characters 26-34 : Type not found : FlxSound
source/LoadingState.hx:16: lines 16-227 : ... Defined in this class
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/effects/chainable/FlxEffectSprite.hx:137: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
source/Subtitle.hx:16: characters 3-9 : Unknown identifier : sounds
source/Subtitle.hx:22: characters 3-8 : Unknown identifier : start
source/DialogueBox.hx:204: characters 18-24 : flixel.addons.text.FlxTypeText has no field sounds
source/DialogueBox.hx:217: characters 18-24 : flixel.addons.text.FlxTypeText has no field sounds
source/DialogueBox.hx:308: characters 16-25 : flixel.addons.text.FlxTypeText has no field resetText
source/DialogueBox.hx:309: characters 16-21 : flixel.addons.text.FlxTypeText has no field start
source/PlayState.hx:1426: characters 72-73 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1426: characters 72-73 : ... For optional function argument 'repeatAxes'
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:94: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:142: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:[15](https://github.com/Euro55222/VsDave-3.0-Early-Android-Port/actions/runs/6918165407/job/18820120153#step:10:16)0: characters 18-19 : flixel.util.FlxAxes has no field x
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:151: characters 18-19 : flixel.util.FlxAxes has no field y
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:413: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:419: characters 21-22 : flixel.util.FlxAxes has no field x
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:420: characters 21-22 : flixel.util.FlxAxes has no field y
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:423: characters 21-22 : flixel.util.FlxAxes has no field x
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:424: characters 21-22 : flixel.util.FlxAxes has no field y
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:426: characters 21-22 : flixel.util.FlxAxes has no field x
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:427: characters 21-22 : flixel.util.FlxAxes has no field y
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:429: characters 21-22 : flixel.util.FlxAxes has no field x
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:429: characters 44-45 : flixel.util.FlxAxes has no field x
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:430: characters 21-22 : flixel.util.FlxAxes has no field y
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:430: characters 44-45 : flixel.util.FlxAxes has no field y
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:450: characters 20-21 : flixel.util.FlxAxes has no field x
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:456: characters 20-21 : flixel.util.FlxAxes has no field y
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:493: characters 30-31 : flixel.util.FlxAxes has no field x
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:494: characters 30-31 : flixel.util.FlxAxes has no field y
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:191: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:209: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:212: characters 19-20 : flixel.util.FlxAxes has no field x
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:221: characters 19-20 : flixel.util.FlxAxes has no field y
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:262: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:312: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:3[16](https://github.com/Euro55222/VsDave-3.0-Early-Android-Port/actions/runs/6918165407/job/18820120153#step:10:17): characters 19-20 : flixel.util.FlxAxes has no field x
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:325: characters 19-20 : flixel.util.FlxAxes has no field y
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:[18](https://github.com/Euro55222/VsDave-3.0-Early-Android-Port/actions/runs/6918165407/job/18820120153#step:10:19)2: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
source/SelectLanguageState.hx:37: characters 66-67 : Int should be flixel.util.FlxAxes
source/SelectLanguageState.hx:37: characters 66-67 : ... For optional function argument 'repeatAxes'
/home/runner/haxelib/flixel-addons/3,2,1/flixel/addons/transition/FlxTransitionableState.hx:81: characters [20](https://github.com/Euro55222/VsDave-3.0-Early-Android-Port/actions/runs/6918165407/job/18820120153#step:10:21)-30 : Field startOutro is declared 'override' but doesn't override any field
source/SUtil.hx:2[21](https://github.com/Euro55222/VsDave-3.0-Early-Android-Port/actions/runs/6918165407/job/18820120153#step:10:22): characters 4-9 : Type not found : Toast
source/SUtil.hx:[22](https://github.com/Euro55222/VsDave-3.0-Early-Android-Port/actions/runs/6918165407/job/18820120153#step:10:23)7: characters 4-9 : Type not found : Toast
Error: Process completed with exit code 1.

**Is there a way to fix it?**

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

**Comment by KarimAkra** [comment]
Seems like you're using incorrect haxelib versions please run these commands
`
haxelib install hmm
haxelib run hmm install
`
To get all the haxelib we use

**Comment by Euro55222** [comment]
Thank you very much for the advice.

**Comment by Euro55222** [comment]
**I received the wrong order**

Error: No such version haxelib for library hmm
Error: Process completed with exit code 1.

**Comment by KarimAkra** [comment]
> **I received the wrong order**
> 
> Error: No such version haxelib for library hmm Error: Process completed with exit code 1.

Run
`
haxelib install hmm
`
Then run
`
haxelib run hmm install
`

**Comment by Euro55222** [comment]
Okay, I'll try again.

> > **I received the wrong order**
> > Error: No such version haxelib for library hmm Error: Process completed with exit code 1.
> 
> Run `haxelib install hmm` Then run `haxelib run hmm install`
