### ISSUE TITLE
Win icons

### ISSUE THREAD

**Issue by Seifkarimabaza6** [MobilePorting/FNF-PsychEngine-Mobile#37]
### Describe your bug here.

So I downloaded win icons script on fnf android but the win icons go a layer behind the health bar

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

Haven't changed anything

**Comment by KarimAkra** [comment]
This has nothing to do with the port
The lua script you're using is probably outdated
