### ISSUE TITLE
Pls fix

### ISSUE THREAD

**Issue by Epicguy500** [MobilePorting/FNF-PsychEngine-Mobile#38]
### Describe your bug here.

For some reason when i install a mod the text becomes % any way to fix?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by KarimAkra** [comment]
Can you show us a screenshot?

**Comment by mcagabe19** [comment]
ShadowMario's issue probably if you we're downloaded release build

**Comment by KarimAkra** [comment]
I think the mods you're using has the old alphabet sprite

**Comment by KarimAkra** [comment]
closed due to no respons
