### ISSUE TITLE
how

### ISSUE THREAD

**Issue by TomVN1230101** [MobilePorting/FNF-PsychEngine-Mobile#39]
### Describe your problem here.

help me fix
source/states/PlayState.hx:36: characters 8-46 : Type not found : flixel.addons.display.FlxRuntimeShader
source/psychlua/FunkinLua.hx:13: characters 8-46 : Type not found : flixel.addons.display.FlxRuntimeShader
C:/HaxeToolKit/haxe/lib/flixel-addons/3,0,2/flixel/addons/transition/FlxTransitionableState.hx:81: lines 81-90 : Warning : switchTo is deprecated, use startOutro
source/states/PlayState.hx:3801: characters 51-67 : Type not found : FlxRuntimeShader

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by KarimAkra** [comment]
update your flixel version

**Comment by mcagabe19** [comment]
update ur everything to latest
