### ISSUE TITLE
is this mod free to use?

### ISSUE THREAD

**Issue by FacunMax** [MobilePorting/FNF-PsychEngine-Mobile#40]
### What is your question?

is this mod free to use, i mean, i can use it for my mod? i obviusly give credits

**Comment by KarimAkra** [comment]
Yes that's why it's open source

**Comment by mcagabe19** [comment]
this is a "mobile port" not a "mod"

**Comment by MemeHovy** [comment]
> ### What is your question?
> is this mod free to use, i mean, i can use it for my mod? i obviusly give credits

This is a port, and yeah, that’s the point of it being open source idiot
