### ISSUE TITLE
when in character editor in p.e 0.7.2, I pressed save character, but it didn't save.

### ISSUE THREAD

**Issue by levi-go64** [MobilePorting/FNF-PsychEngine-Mobile#41]
### Describe your bug here.

https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/96037133/3b99cb95-0333-4fb5-b4ba-56557eb6b29b

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by KarimAkra** [comment]
Should be fixed now in newer builds
