### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by Dandantheman231** [MobilePorting/FNF-PsychEngine-Mobile#42]
### Describe your bug here.

It kept on telling me to make a psych engine folder (FOR EXTERNAL APK) when it was already made.

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
enable all files access for psych engine

**Comment by mcagabe19** [comment]
can be finded in settings > search > All Files Access

**Comment by Dandantheman231** [comment]
Oh ok thx

**Comment by Dandantheman231** [comment]
I got another problem, the game keeps crashing, why is that?

**Comment by mcagabe19** [comment]
if you have a phone with a manufacturer like xioami and vivo u can't really run it
