### ISSUE TITLE
0.7.2h just straight up doesn't work.

### ISSUE THREAD

**Issue by biomseed** [MobilePorting/FNF-PsychEngine-Mobile#44]
### Describe your bug here.

I enabled all files access, so it's not that. The game closes on startup, and then afterwards when I try to open it, it's just a black screen. Back button does nothing. 0.7.2 works fine.

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by mcagabe19** [comment]
probably fixed now try redownload
