### ISSUE TITLE
The arrow buttons in menus they don't work

### ISSUE THREAD

**Issue by OskarWii64** [MobilePorting/FNF-PsychEngine-Mobile#45]
### Describe your bug here.

The buttons don't work in main menu, freeplay menu, etc. Please fix it

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
wipe psych engine's data and rerun

**Comment by mcagabe19** [comment]
> Still does'n work pd: I using the data ver.

reinstall our psych from releases

**Comment by OskarWii64** [comment]
It works now thanks

**Comment by mcagabe19** [comment]
👍
