### ISSUE TITLE
About The External

### ISSUE THREAD

**Issue by Z4CK1234** [MobilePorting/FNF-PsychEngine-Mobile#47]
### Describe your problem here.

When I Open The Game It Says Error! Then Please let Create A Folder In /Storege/Emulated/0/.PsychEngine I Follow The Instructions Correctly But When I Open The Game Again The Message Appear Again And I Open The Assets Folder There's A Three Missing Folders Characters, Images, And Sounds Folder Maybe That's The Problem Why The Game Is Not Working I Hope You Fix This.

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

I Didn't Edit Anything I'm Not Actually A Coder

**Comment by KarimAkra** [comment]
this was fixed in later builds, please download it from (here)[https://github.com/MobilePorting/FNF-PsychEngine-Mobile/releases/tag/0.7.2h]

**Comment by mcagabe19** [comment]
seem like it's broken even in releases needed to check

**Comment by mcagabe19** [comment]
@Z4CK1234 go psych engine info > permissions > enable storage permisson

**Comment by Z4CK1234** [comment]
Oh Is Because The Storage Permission Was Not Allowed Ok. Thanks For Fixing The Problem @mcagabe19
