### ISSUE TITLE
Key trigger failure

### ISSUE THREAD

**Issue by Ajwyunsx** [MobilePorting/FNF-PsychEngine-Mobile#48]
### Describe your bug here.

Why can't I press up and down in 0.7.2? Other versions of android 13 can be used, but android 13 can't be used 

https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/107187521/be630c93-6d9a-43f6-b998-d1ba3aed8e2f

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by mcagabe19** [comment]
clear your psych engine data (backup mods first)
