### ISSUE TITLE
Bugs in the files 

### ISSUE THREAD

**Issue by Gatinhagames098** [MobilePorting/FNF-PsychEngine-Mobile#49]
### Describe your bug here.

So, I had to find bugs when getting a buggy mods or assets, because of this it prevented the fun from being used, so going to a slightly old version for the mods to work

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

I changed nothing

**Comment by moxie-coder** [comment]
you didn't even explain anything, how can we fix something you don't explain?

**Comment by BambStrident** [comment]
The External Apk Says: Emulated/0/. PsychEngine But I Do These Obligations but when I finish and enter the game again, It's the same thing appearing.

**Comment by BambStrident** [comment]
![Screenshot_20240104-112628](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/154909801/c91fb8ea-71ab-4ead-9bf5-16fcdbceedd7)

**Comment by BambStrident** [comment]
![Uploading Screenshot_20240104-112716.png…]()

**Comment by KarimAkra** [comment]
Try updating your game from [here](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/releases/tag/0.7.2h) it fixed this issue
