### ISSUE TITLE
Don't Working Buttons

### ISSUE THREAD

**Issue by Deskarpion** [MobilePorting/FNF-PsychEngine-Mobile#52]
### Describe your bug here.

The buttons do not perform their functionality, they do not scroll

Here is the video
https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/99749470/7fe03e45-3fc1-4de2-b62f-084bbc396179

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

I don't change something

**Comment by mcagabe19** [comment]
clean your psych engine data and reopen the game

**Comment by Deskarpion** [comment]
> clean your psych engine data and reopen the game

I just deleted all files, assets, mods, reinstalled assets, it still doesn't work

**Comment by Deskarpion** [comment]
> Yeah you shouldn't do that, the problem seems to be with the input of the buttons not really affecting the menu, removing stuff from the engine won't fix it. it's a problem in the engine itself. Pretty weird stuff tho, could you give more info about your phone?

Name::Realme XT
UI Version::2.0
Android Version::11
Processor::Qualcomm SDM712 8 core processes
RAM::8 GB
Model::RMX1921

**Comment by Deskarpion** [comment]
> Yeah you shouldn't do that, the problem seems to be with the input of the buttons not really affecting the menu, removing stuff from the engine won't fix it. it's a problem in the engine itself. Pretty weird stuff tho, could you give more info about your phone?

This is don't Engine problem i think, controls can't change keybinds while porting to android

**Comment by Deskarpion** [comment]
Wipe all data of Psych Engine folder don't help with chance: 100%

**Comment by KarimAkra** [comment]
You need to clear the app data in your settings

**Comment by Deskarpion** [comment]
> You need to clear the app data in your settings

Don't work

**Comment by Deskarpion** [comment]
I reinstalled FNF PE to external
