### ISSUE TITLE
I can't seem to reload audio on the chart editor

### ISSUE THREAD

**Issue by Youstoopid1** [MobilePorting/FNF-PsychEngine-Mobile#53]
### Describe your problem here.

I'm on the external build. I decided to try charting a song that I put into the mods folder, it has the inst and vocal files, and the folder is named correctly, but whenever I try typing in the song and reloading the audio, it just gives me a crash error.

![Screenshot_20240111_192940](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/132790240/23da464d-66fb-44f3-942c-701c1d79a8d4)

(Note: I guess it says I'm modding from source, but I'm just adding mods into the folder, idk if that's still source lol)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Desktop (Linux, Windows or Mac)

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited the songs folder in the assets folder, i put a new song folder in it.

**Comment by moxie-coder** [comment]
keep in mind you shouldn’t directly add files into the assets folders, instead of the mods folders of you’re not using source code

**Comment by Youstoopid1** [comment]
Even so, Ive tried that already, same error, so I'm at a loss.

**Comment by KarimAkra** [comment]
Looking at the crach seems like you're using an old build
Can you update it from [release](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/releases/tag/0.7.2h)?

**Comment by Youstoopid1** [comment]
I'm using 0.72 h, there doesn't seem to be an old version as I downloaded the game like yesterday

**Comment by mcagabe19** [comment]
check if inst and voices are not lowercase

**Comment by Youstoopid1** [comment]
They are both uppercase, and for good measure I checked if changing them to lowercase did anything, but no.

**Comment by Youstoopid1** [comment]
Ok I fixed the issue, for whatever reason the "songs" folder needed to be in the "mods" folder, and not within the extracted mod template folder. So we good now.

**Comment by moxie-coder** [comment]
> Ok I fixed the issue, for whatever reason the "songs" folder needed to be in the "mods" folder, and not within the extracted mod template folder. So we good now.

told you so
