### ISSUE TITLE
Crash the after select any song instantly

### ISSUE THREAD

**Issue by TDoodleF** [MobilePorting/FNF-PsychEngine-Mobile#54]
### Describe your bug here.

Select any song will crash the game because back to home menu

### Crash Log or logcat logs (if existing)

```bash
Remember fix this crash
```

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, because of the crash problem

**Comment by moxie-coder** [comment]
@TDoodleF we need logs if we're gonna fix the issue

**Comment by KarimAkra** [comment]
You have not given us anything that's useful to be able to attempt and fix this issue

**Comment by mcagabe19** [comment]
already fixed
