### ISSUE TITLE
ios  cannot open

### ISSUE THREAD

**Issue by fg133266** [MobilePorting/FNF-PsychEngine-Mobile#55]
### Describe your problem here.

When I installed and turned on 0.7.2psych, it blinked

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

iOS

### Did you edit anything in this build? If so, mention or summarize your changes.

I didn't do anything

**Comment by KarimAkra** [comment]
Give more info please

**Comment by fg133266** [comment]
> Give more info please

It's okay, I was able to open lol normally after disconnecting the network lol

**Comment by mcagabe19** [comment]
I'll make Check For Updates disabled for iOS
