### ISSUE TITLE
Chart editor option is gone

### ISSUE THREAD

**Issue by ThatOneRatt** [MobilePorting/FNF-PsychEngine-Mobile#56]
### Describe your bug here.

So basically I wanted to chart a song but the chart editor option just wasnt there for some reason
![Screenshot_2024-01-14-22-20-12-933_com shadowmario psychengine](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/104328319/2e5b53e1-7ea5-4610-83e2-8b08d0ea150c)

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by KarimAkra** [comment]
Sorry for that
This got fixed now
You can either use actions build(which is unstable) or just wait for a new stable release to come out...
