### ISSUE TITLE
Packed Mod Shit

### ISSUE THREAD

**Issue by HogMedioScorched** [MobilePorting/FNF-PsychEngine-Mobile#57]
### Describe your bug here.

![Screenshot_20240113-200641](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/156556823/b2bae6ef-ec0d-4b0c-95d4-8dea4d7d5abb)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i put commas i fixed all typos and other shit

**Comment by moxie-coder** [comment]
are you on the latest version?

**Comment by moxie-coder** [comment]
specifically [this](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/actions/runs/7522161393)

**Comment by HogMedioScorched** [comment]
No, im using vlgmods apk

**Comment by HogMedioScorched** [comment]
I will optimize build

**Comment by moxie-coder** [comment]
> No, im using vlgmods apk

dude, how the fuck is this even related then?
