### ISSUE TITLE
Keyboard not showing up

### ISSUE THREAD

**Issue by JakeIzNutSus** [MobilePorting/FNF-PsychEngine-Mobile#58]
### Describe your problem here.

I was making a sprite and i was trying to make a JSON for it, for some reason, my keyboard wouldn't show up. That is all that i can describe about this issue, can you fix it?

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

**Comment by mcagabe19** [comment]
in where?

**Comment by moxie-coder** [comment]
closing due to no reply
