### ISSUE TITLE
Keyboard not showing up

### ISSUE THREAD

**Issue by LuizFelipePlay** [MobilePorting/FNF-PsychEngine-Mobile#59]
### Describe your bug here.

Bassically in any editor we use the keyboard for type song names spritesheet names but keyboard now showing (dialogue editor works) but fix this

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
duplicate of https://github.com/MobilePorting/FNF-PsychEngine-Mobile/issues/58

**Comment by Stefan2008Git** [comment]
> duplicate of #58

LMFAO. He is 11 years old :skull:
