### ISSUE TITLE
Scripts not working 

### ISSUE THREAD

**Issue by andrekane** [MobilePorting/FNF-PsychEngine-Mobile#60]
### Describe your bug here.

Nothing here

### Crash Log or logcat logs (if existing)

```bash
Why are you here??
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by moxie-coder** [comment]
> ### Describe your bug here.
> Nothing here
> 
> ### Crash Log or logcat logs (if existing)
> ```shell
> Why are you here??
> ```
> 
> ### Are you modding a build from source or with Lua?
> Lua
> 
> ### What is your build target?
> Android
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> No

kys
