### ISSUE TITLE
My antivirus is swearing at the app

### ISSUE THREAD

**Issue by AyderProgramic** [MobilePorting/FNF-PsychEngine-Mobile#61]
### What is your question?

It's cursing because "AndroidOS.Evo" 
Is it safe?

**Comment by moxie-coder** [comment]
yes, it's open source, duh

**Comment by mcagabe19** [comment]
it's due google's certificate system issue

**Comment by AyderProgramic** [comment]
One more question, I noticed that this app consumes internet traffic

**Comment by mcagabe19** [comment]
checks updates ofc it's
