### ISSUE TITLE
Bug note long

### ISSUE THREAD

**Issue by 8eg1ner** [MobilePorting/FNF-PsychEngine-Mobile#63]
### Describe your bug here.

For some reason the long note don't add health its kinda like add 1 health this make not fun bc there a mod add health drain 

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by 8eg1ner** [comment]
https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/134765627/ea4a9e63-96df-4b60-9a82-ed447bf4f575

Just see it

**Comment by moxie-coder** [comment]
1. issues with mods is not *our* problem
2. make sure you don't certain settings enabled that can disable that

**Comment by 8eg1ner** [comment]
https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/134765627/58a06083-275a-43c1-baa9-471da5bb0eac

How about this then i try to delete all and even reset it,its now working

**Comment by moxie-coder** [comment]
hmm, if this is without mods & you resetted all your settings, alright then

**Comment by mcagabe19** [comment]
uncheck "Sustains As One Note" in options

**Comment by moxie-coder** [comment]
> uncheck "Sustains As One Note" in options

oh I didn't know about that option, even though I suggested to check settings **before**
