### ISSUE TITLE
How can i modify Mobile Controls X and Y?

### ISSUE THREAD

**Issue by StarmanFR** [MobilePorting/FNF-PsychEngine-Mobile#65]
### What is your question?

I wanted to move the controls X and Y ingame when playing but idk how 
can it be modified thru HScript?

**Comment by KarimAkra** [comment]
The best way to do this would be
```
runHaxeCode([[
MusicBeatState.instance.mobileControls.virtualPad.buttonLeft.x = x;
]])
```
Replace virtualPad with hitbox for hitbox and buttonLeft can be replaced with buttonUp, buttonDown and buttonRight

**Comment by StarmanFR** [comment]
It woorkedd! Thank you so muchh!!!  ^ᴗ^
