### ISSUE TITLE
Open song with mechanics by crashing the game

### ISSUE THREAD

**Issue by TDoodleF** [MobilePorting/FNF-PsychEngine-Mobile#66]
### Describe your bug here.

If select any song with bunch of mechanics will crash the game then appear on the home screen
Can you fix it pls

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, because of the crash problem

**Comment by TDoodleF** [comment]
Mechanics are both:
Note event and mechanic event is too many mechanics will crash by playing the song
Thanks for reading I hope you fix this issue

**Comment by moxie-coder** [comment]
issues with mods are not issues with the port
