### ISSUE TITLE
Note mechanic and Event crash bug

### ISSUE THREAD

**Issue by TDoodleF** [MobilePorting/FNF-PsychEngine-Mobile#67]
### Describe your bug here.

I was play any song with events/Note event too many will be crash but the song are fine as well

### Crash Log or logcat logs (if existing)

```bash
Too many events and Note mechanics are crash
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, because the event are broken and the game crash because the song are fine

**Comment by mcagabe19** [comment]
I swear to god

**Comment by moxie-coder** [comment]
shut the fuck up & don't open duplicates
