### ISSUE TITLE
Song crashed without reason

### ISSUE THREAD

**Issue by RedcappedmelonYT** [MobilePorting/FNF-PsychEngine-Mobile#68]
### Describe your bug here.

hello, so my song crashed without reason and idk what happened, i checked all and they were fine.

### Crash Log or logcat logs (if existing)

```bash
Null Object Reference
flixel/animation/FlxAnimationController.hx [line 739]
source/objects/Note.hx [line 420]
source/objects/Note.hx [line 398]
source/objects/Note.hx [line 370]
source/objects/Note.hx [line 146]
source/objects/Note.hx [line 234]
source/states/PlayState.hx [line 1360]
source/states/PlayState.hx [line 519]
flixel/FlxGame.hx [line 642]
flixel/FlxGame.hx [line 729]
flixel/FlxGame.hx [line 682]
flixel/FlxGame.hx [line 556]
openfl/events/EventDispatcher.hx [line 444]
openfl/display/DisplayObject.hx [line 1400]
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

none

**Comment by moxie-coder** [comment]
invalid note textures/xml, make sure you didn’t screw up your note xml
