### ISSUE TITLE
Scripts dont work

### ISSUE THREAD

**Issue by andrekane** [MobilePorting/FNF-PsychEngine-Mobile#69]
### Describe your bug here.

Nothing

### Crash Log or logcat logs (if existing)

```bash
No
```

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

I get script in script folder and did not work

**Comment by enkhuush10** [comment]
You need to put it in "data/"song name""

**Comment by moxie-coder** [comment]
you didn’t give a lot of information, we need more info like logs

**Comment by BernardoGP4504** [comment]
> You need to put it in "data/_song name_"

Not necessarily.

**Comment by BernardoGP4504** [comment]
If you are loading scripts, yes you are modding.
Also, give more information @andrekane

**Comment by KarimAkra** [comment]
legend says they left for milk

**Comment by mcagabe19** [comment]
no dad jokes in issues >:(

**Comment by KarimAkra** [comment]
yuh huh

**Comment by andrekane** [comment]
So, you dont put in the scripts folder?
