### ISSUE TITLE
Can't Even Import Character's

### ISSUE THREAD

**Issue by RefuestJeremiah** [MobilePorting/FNF-PsychEngine-Mobile#70]
### Describe your bug here.

I Been Trying to import characters but it keeps saying NO CHARACTER ANIMATION like its broken or something please fix this

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I just Downloaded the build and then tried to import a character

**Comment by mcagabe19** [comment]
give us a video

**Comment by RefuestJeremiah** [comment]
How do import the video?

**Comment by mcagabe19** [comment]
you can use like mediafire or imgur

**Comment by RefuestJeremiah** [comment]
https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/123858585/6cb61d03-ac17-484c-88db-48591833d72a

**Comment by mcagabe19** [comment]
are you sure you downloaded `EXTERNAL` build and u selected the mod in `MasterEditorMenu`?

**Comment by RefuestJeremiah** [comment]
> are you sure you downloaded `EXTERNAL` build and u selected the mod in `MasterEditorMenu`?

What?

**Comment by RefuestJeremiah** [comment]
> are you sure you downloaded `EXTERNAL` build and u selected the mod in `MasterEditorMenu`?

Oh shoot i downloaded DATA

**Comment by mcagabe19** [comment]
see
https://github.com/MobilePorting/FNF-PsychEngine-Mobile/wiki/Installing-Mods

**Comment by RefuestJeremiah** [comment]
Sorry, Thanks for helping me

**Comment by mcagabe19** [comment]
👍
