### ISSUE TITLE
"ERROR: No animation found" even though it's fine for the characters name

### ISSUE THREAD

**Issue by RedcappedmelonYT** [MobilePorting/FNF-PsychEngine-Mobile#71]
### Describe your bug here.

when i use my character, there was no image and animation, instead, uses the flixel logo which is annoying asf. like it's fine bro, why?

### Crash Log or logcat logs (if existing)

```bash
Null Object Reference
flixel/graphics/tile/FlxDrawQuadsItem.hx [line 119]
flixel/FlxCamera.hx [line 772]
flixel/FlxGame.hx [line 875]
flixel/FlxGame.hx [line 563]
openfl/events/EventDispatcher.hx [line 444]
openfl/display/DisplayObject.hx [line 1400]
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Desktop (Linux, Windows or Mac)

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by RedcappedmelonYT** [comment]
no im on mobile lol, also about the error, when i make a custom character with the same name and xml, it uses flixel logo

**Comment by KarimAkra** [comment]
where are you placing the character image? and are you sure you're selecting your mod before entering the Character Editor ??

**Comment by mcagabe19** [comment]
> no im on mobile lol, also about the error, when i make a custom character with the same name and xml, it uses flixel logo

https://github.com/MobilePorting/FNF-PsychEngine-Mobile/wiki/Installing-Mods
