### ISSUE TITLE
How to change the shift button to the space button? 

### ISSUE THREAD

**Issue by Michae12098** [MobilePorting/FNF-PsychEngine-Mobile#72]
### Describe your problem here.

In some songs from the mods the dodge button is assigned to space, but since
the dodge button is assigned to the shift button on android, I just can't dodge.

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

**Comment by KarimAkra** [comment]
You have to edit the mod lua to have the extra buttons working with it's mechanics

Please check the [extra buttons lua functions wiki](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/wiki/Mobile-Lua-API#extra-buttons-functions) for more info of how you can make them work with a mod mechanics

**Comment by Michae12098** [comment]
Thank you
