### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Sonic123319** [MobilePorting/FNF-PsychEngine-Mobile#73]
### Describe your problem here.

When I want to put scripts I don't get the folder and the custom arrows are not what they are when I put a mod

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

**Comment by moxie-coder** [comment]
I don't get this, could you elaborate further??

**Comment by moxie-coder** [comment]
actually wait, you need to make a scripts folder in mods, and old Notes that aren't made with 0.6 or made with 0.7.X, they will not work, it's been changed how they work, use this [example instead](https://files.catbox.moe/hs8ayz.lua)

**Comment by Sonic123319** [comment]
Since what version do the scripts and custom arrows work?

**Comment by moxie-coder** [comment]
> Since what version do the scripts and custom arrows work?

they’ve worked since 0.4, we use 0.7.3 so old scripts and shit won’t work

**Comment by Sonic123319** [comment]
Also when I want to play the deep dark song in the fnf minecraft mod it tells me Invalid chart 48 at Position 118361 Why do I get that?

**Comment by moxie-coder** [comment]
okay this is just becoming unrelated to the problem at hand here
