### ISSUE TITLE
Screensaver option

### ISSUE THREAD

**Issue by Stefan2008Git** [MobilePorting/FNF-PsychEngine-Mobile#76]
### What is your question?

What is the limited time of screensaver for system settings?

**Comment by KarimAkra** [comment]
![Screenshot_20240215_064051_com android settings](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/144803230/37f7a1e1-a126-4e24-ab69-18f010f24d4b)
It depends on your phone settings

**Comment by Stefan2008Git** [comment]
> ![Screenshot_20240215_064051_com android settings](https://private-user-images.githubusercontent.com/144803230/304952275-37f7a1e1-a126-4e24-ab69-18f010f24d4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5OTI1MjksIm5iZiI6MTcwNzk5MjIyOSwicGF0aCI6Ii8xNDQ4MDMyMzAvMzA0OTUyMjc1LTM3ZjdhMWUxLWExMjYtNGUyNC1hYjY5LTE4ZjAxMGYyNGQ0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQxMDE3MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzRlNWVmZTViOTAwMWU4NTYyMTE2Njg2NjBmOTg3MTMzMmMwYWY0MzZlNDY3YWJlZjAyY2MwZGI1ZThjZTFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n4SE1MPrek84Qu9nj-WT9K95_NFrQZbBNxZy_Q90Ru8) It depends on your phone settings

O, wait. We had the same settings
