### ISSUE TITLE
"shader function: NO OBJECT WITH A TAG OF "2" EXIST" (glitch effect on a stage)

### ISSUE THREAD

**Issue by RedcappedmelonYT** [MobilePorting/FNF-PsychEngine-Mobile#77]
### Describe your problem here.

so i added a glitch effect to my stage and then this error appeared, why??
![Screenshot_20240217_200900](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/155062363/e6835105-d5ae-4c3f-ad8d-17972823ca3b)

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

i am not

**Comment by mcagabe19** [comment]
https://github.com/MobilePorting/FNF-PsychEngine-Mobile/wiki/Shaders-Lua-API#addglitcheffecttagstring-objectstring-wavespeedfloat-wavefrqfloat-waveampfloat

**Comment by KarimAkra** [comment]
he's using FlxRuntimeShader not these
anyways it's your script issue not the port.
