### ISSUE TITLE
Songs Not Syncing When Lag Spikes Hits.

### ISSUE THREAD

**Issue by AuroraStarlight264** [MobilePorting/FNF-PsychEngine-Mobile#78]
### Describe your bug here.

Hello, I would like you to fix the song sync because when I play one of my spammy song I get laggy (because of 3gb of ram) and I turned on every optimization setting I find, and I wonder if you can get it fixed in Psych Engine 0.7.4.

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I did not modded to hard and break the syncing the song

**Comment by moxie-coder** [comment]
hardware issues is something we can't fix

**Comment by Stefan2008Git** [comment]
@moxie-coder Dave and Bambi enjoyer LMFAO

**Comment by Stefan2008Git** [comment]
> hardware issues is something we can't fix

Yep, yep, yep
