### ISSUE TITLE
Cant add mod

### ISSUE THREAD

**Issue by Attila2012** [MobilePorting/FNF-PsychEngine-Mobile#79]
### Describe your bug here.

I cant paste mod into the mods folder 
![Screenshot_20240220-194740](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/160651562/8e024388-d63d-49e2-a060-2e3956991c24)

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
try this
![Screenshot_20240220_215019_Discord](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/82843871/900ef85e-5091-4968-9f73-d7b38c511ae4)
