### ISSUE TITLE
Well when i use a Devlog version in chart editor and in game, the events don't work, even when I press load events and there is already events.json file, but all the events don't appear.

### ISSUE THREAD

**Issue by levi-go64** [MobilePorting/FNF-PsychEngine-Mobile#81]
### Describe your bug here.

![Screenshot_20240223_064033](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/96037133/368e9360-22be-4c01-9c36-8a5855f60f65)

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by moxie-coder** [comment]
buddy, the chart editor isn't finished, it's a dev build so that's to be expected, it'll be fixed soon

**Comment by levi-go64** [comment]
Oh okay

**Comment by moxie-coder** [comment]
and don't put the issue in the fucking title

**Comment by levi-go64** [comment]
Oh yeah i forgot, sorry.
