### ISSUE TITLE
how to remove lag for spammy songs?

### ISSUE THREAD

**Issue by RedcappedmelonYT** [MobilePorting/FNF-PsychEngine-Mobile#83]
### What is your question?

So, i made some spammy songs that have a lot of notes, but the engine kepts lagging. How to remove the lag in this?

**Comment by BernardoGP4504** [comment]
Don't. Just don't make spammy songs

Jk. Turn off antialiasing, notesplashes and pop-up score options

**Comment by moxie-coder** [comment]
![ThatsTheNeatPartYouDontInvincibleGIF](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/124418090/c463b602-1ad3-4f49-9b25-707cc902b8ab)

**Comment by Stefan2008Git** [comment]
> ### What is your question?
> So, i made some spammy songs that have a lot of notes, but the engine kepts lagging. How to remove the lag in this?

Bahahahaha, blud is still playing the shitty asshole spammy songs fr

**Comment by RedcappedmelonYT** [comment]
> > ### What is your question?
> > So, i made some spammy songs that have a lot of notes, but the engine kepts lagging. How to remove the lag in this?
> 
> Bahahahaha, blud is still playing the shitty asshole spammy songs fr

shut up, nobody cares

**Comment by moxie-coder** [comment]
> > > ### What is your question?
> > > So, i made some spammy songs that have a lot of notes, but the engine kepts lagging. How to remove the lag in this?
> > 
> > 
> > Bahahahaha, blud is still playing the shitty asshole spammy songs fr
> 
> shut up, nobody cares


https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/124418090/7a2e6949-3469-4567-a4f2-8bdfcc790d3c
