### ISSUE TITLE
Dodge/Space Button Bug

### ISSUE THREAD

**Issue by Z4CK1234** [MobilePorting/FNF-PsychEngine-Mobile#84]
### Describe your bug here.

https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/129644239/ef4c4397-b5ae-4c08-83bb-dc79b88a6471

https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/129644239/c0fc1412-d102-49ef-9cb3-78a87e34aa80
The Space Button Not Working And Turning Off Mods Can Cause Crash

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

I Didn't Edit Anything

**Comment by moxie-coder** [comment]
well, I would make sure you're on the latest version, and this might be due to an incompatible mod, not every mod is gonna work
