### ISSUE TITLE
Crashes instantly when opening the game

### ISSUE THREAD

**Issue by VikryCraftID** [MobilePorting/FNF-PsychEngine-Mobile#90]
### Describe your bug here.

It doesn't let me play the game. 
I use canary release (External)

https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/109458330/c1395735-fc5b-4603-a85e-119dc80ac98b

### Crash Log or logcat logs (if existing)

```bash
no logcat
```

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't.

**Comment by mcagabe19** [comment]
fixed but didn't included on devbuild yet
