### ISSUE TITLE
Song load error

### ISSUE THREAD

**Issue by Deskarpion** [MobilePorting/FNF-PsychEngine-Mobile#91]
### Describe your bug here.

When Psych Engine trying to load song, makes crash

### Crash Log or logcat logs (if existing)

```bash
Null Object Reference
source/mobile/flixel/FlxHitbox.hx [line 42]
source/mobile/objects/MobileControls.hx [line 65]
source/mobile/objects/MobileControls.hx [line 36]
source/backend/MusicBeatState.hx [line 46]
source/states/PlayState.hx [line 624]
flixel/FlxGame.hx [line 642]
flixel/FlxGame.hx [line 729]
flixel/FlxGame.hx [line 682]
flixel/FlxGame.hx [line 556]
openfl/events/EventDispatcher.hx [line 444]
openfl/display/DisplayObject.hx [line 1400]
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

I didn't

**Comment by mcagabe19** [comment]
go mobile controls settings and reselect extra controls

**Comment by Deskarpion** [comment]
> go mobile controls settings and reselect extra controls

I think you mean it: https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/99749470/17f65b6d-09fd-4f9e-b070-795b143c9d17

**Comment by Deskarpion** [comment]
Fixed: it's getting crashes mods

**Comment by moxie-coder** [comment]
![image](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/124418090/76e41c5d-ab84-40b2-ae45-e6673ab8e0c0)
