### ISSUE TITLE
The next version cannot be opened HELP 

### ISSUE THREAD

**Issue by Hola234tobotos** [MobilePorting/FNF-PsychEngine-Mobile#92]
### Describe your bug here.

Opt al inicio así opt/

### Crash Log or logcat logs (if existing)

```bash
Si existen pero no lo guarde
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No no edite nada

**Comment by mcagabe19** [comment]
I don't look at non-engish and just wait when we release you'll see.

**Comment by Hola234tobotos** [comment]
Thank I speak spain but wait:v
