### ISSUE TITLE
The dev version is trash 

### ISSUE THREAD

**Issue by Hola234tobotos** [MobilePorting/FNF-PsychEngine-Mobile#93]
### Describe your problem here.

They banned me from the server and insulted me and the creator is a paytowin who does not want an external version and that will make the engine a failure 

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
you don't listen to us and don't shut up, send nosense so

**Comment by moxie-coder** [comment]
> ### Describe your problem here.
> They banned me from the server and insulted me and the creator is a paytowin who does not want an external version and that will make the engine a failure
> 
> ### Are you modding a build from source or with Lua?
> I am not modding
> 
> ### What is your build target?
> Android
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> No

![IMG_4956](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/124418090/959e0b27-cf93-454e-a8e4-16b3c944f508)

**Comment by moxie-coder** [comment]
and also this too


https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/124418090/0421ee0a-287f-4291-b0c3-36b4a271f5eb
