### ISSUE TITLE
Cant find it 

### ISSUE THREAD

**Issue by TheDarkGlitch** [MobilePorting/FNF-PsychEngine-Mobile#94]
### Describe your problem here.

Alright so I got the DATA one and whenever I go to andriod data I can't find it at all whenever i want to paste in a mod in the engine I can't find it  

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

**Comment by mcagabe19** [comment]
https://github.com/MobilePorting/FNF-PsychEngine-Mobile/wiki/Installing-Mods

**Comment by TheDarkGlitch** [comment]
> https://github.com/MobilePorting/FNF-PsychEngine-Mobile/wiki/Installing-Mods

What u want me to do in that page? Is there like a specific thing I should do?

**Comment by moxie-coder** [comment]
> > https://github.com/MobilePorting/FNF-PsychEngine-Mobile/wiki/Installing-Mods
> 
> What u want me to do in that page? Is there like a specific thing I should do?

read and learn
