### ISSUE TITLE
Package invalid

### ISSUE THREAD

**Issue by JAMESzaRapper9** [MobilePorting/FNF-PsychEngine-Mobile#98]
### What is your question?

Whenever I try install psychic engine it tells me the package is invalid
Any way?
![Screenshot_20240409_192254_Package installer](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/166538304/ec4aa9ca-2cd4-49bb-a0fb-994d2bab5c31)

**Comment by mcagabe19** [comment]
rename the apk to base.apk, zip it, rename to base.apks and install

**Comment by JAMESzaRapper9** [comment]
> rename the apk to base.apk, zip it, rename the zip to base.apks and install

a-
I'm confused 💀 but I will try 
Thanks

**Comment by JAMESzaRapper9** [comment]
It won't let me rename....?

**Comment by mcagabe19** [comment]
move apk to downloads guh

**Comment by JAMESzaRapper9** [comment]
> move apk to downloads 

I tried changing the name from apk to base.apk still invalid

**Comment by mcagabe19** [comment]
> > move apk to downloads
> 
> I tried changing the name from apk to base.apk still invalid

as I said add the apk to zip and rename zip to base.apks after install and send screenshot of the error

**Comment by JAMESzaRapper9** [comment]
> > > move apk to downloads
> > 
> > 
> > I tried changing the name from apk to base.apk still invalid
> 
> as I said add the apk to zip and rename zip to base.apks after install and send screenshot of the error

![Screenshot_20240409_200728_ZArchiver](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/166538304/fe11d2c2-0780-40ef-926f-1fb6b6de5fa8)

**Comment by JAMESzaRapper9** [comment]
U can also check if I did anything wrong in the rename

**Comment by mcagabe19** [comment]
apk file corrupted. reinstall
