### ISSUE TITLE
Cannot paste files or make it them on android/data - android/obb folder (Android 14)

### ISSUE THREAD

**Issue by Stefan2008Git** [MobilePorting/FNF-PsychEngine-Mobile#99]
### Describe your problem here.

Android version: 14
SDK (API) version: 34

During the Android 11 releases, Google did some changes about the storage type on Android 11 ig if i readed correctly on Reddit page
![Screenshot_2024-04-09-23-03-59-326_com android chrome](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/126715034/41082b65-69f5-4270-b2ad-7407990eea21)
, you cannot transfer anymore files on android/data or android/obb folder because for that you need the **FUCKING**  root enabled on device to get this working as you can see on second screenshot
![Screenshot_2024-04-09-09-12-33-327_ru zdevs zarchiver](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/126715034/71bcb1d7-13da-4b43-bfed-832b0c739b57)

If i remember what @KarimAkra said about new storage method with Java + Lime, he will add it to Psych port because he did it on Codename Engine port. So to fix this instead to add new storage method, you can bring back the old MEDIA and EXTERNAL method for people who actually can't even use the `android/data` or `android/obb` method because is required a root, but since is deprecated and removed, well fuck it then

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

Nah, i am simply here to report some people issue

**Comment by mcagabe19** [comment]
find files app (google one), uninstall updates and do same thing on ZArchiver at Android/data

**Comment by mcagabe19** [comment]
for Android/obb, enable unknown application installs for ZArchiver

**Comment by Stefan2008Git** [comment]
> for Android/obb, enable unknown application installs for ZArchiver

It didn't fucking work because my phone is a shitless

**Comment by mcagabe19** [comment]
you don't really needed to close if issue is not fixed

**Comment by Stefan2008Git** [comment]
> you don't really needed to close if issue is not fixed

I tried many times and it didn't work. If you want to know what is my phone, well it's a Redmi Note 12 4G NFC

**Comment by Stefan2008Git** [comment]
> > you don't really needed to close if issue is not fixed
> 
> I tried many times and it didn't work. If you want to know what is my phone, well it's a Redmi Note 12 4G NFC

And it's a shitless one with 4GB of RAM 💀

**Comment by mcagabe19** [comment]
it's not model releated tho, it's due android 14

**Comment by Stefan2008Git** [comment]
> > you don't really needed to close if issue is not fixed
> 
> I tried many times and it didn't work. If you want to know what is my phone, well it's a Redmi Note 12 4G NFC

Alright, then i will re-open it

**Comment by Stefan2008Git** [comment]
> it's not model releated tho, it's due android 14

And that's why i hate my phone
